"""baseline v2（squash 2026-08-04，取代 a1d7e3f92b64 為止的 15 支 migration）

⚠️ **與前一版 baseline（4ac23d6d20b4）的關鍵差異：不使用 `metadata.create_all()`。**

`create_all` 型 baseline 的語意會隨 `tables.py` 漂移 —— 它建出來的是「執行當下的 tables.py」
而非「本 revision 當下的 schema」。這正是 2026-08-04 實測到的鏈斷根因：表在 f4c9a2e81b57
改名為 `reviews` 之後，舊 baseline 直接建出新表名，其後引用 `product_reviews` 的 migration
全部撞 `UndefinedTable`（fresh DB 跑 `alembic upgrade head` 斷在
`ALTER TABLE product_reviews RENAME lst_dt_go TO go_date`）。現況被 `docker-entrypoint.sh`
的雙軌分流遮住 —— 空庫走 create_all+stamp、從不跑鏈，所以沒人發現。

本檔以**凍結的顯式 DDL** 定義 squash 當下的 17 張表，從此 baseline 的產出與 `tables.py` 解耦：
- 後續 migration 有確定的起點，鏈可從真正的空庫跑到 head（由 `tests/test_schema_parity.py` 守住）
- 本檔可經 `alembic upgrade --sql` 產出純 SQL 交 DBA 執行（規範 §四要求 DDL 由 DBA 執行）

⚠️ **既有環境的升級路徑**：squash 後 `alembic_version` 仍是 a1d7e3f92b64，但該 revision 檔已刪 →
`alembic upgrade head` 會拋 `Can't locate revision`。`docker-entrypoint.sh` 已補相容邏輯：
認不得的版本查 `datapack.LEGACY_COMPATIBLE_HEADS` 對照表 stamp 到本 revision 再 upgrade。

Revision ID: 94e60400715b
Revises:
Create Date: 2026-08-04

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94e60400715b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """一次建齊 squash 當下的 17 張表（顯式 DDL，不依賴 tables.py）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_feedback",
        sa.Column("oid", sa.Text(), nullable=False),
        sa.Column("created_datetime", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("score", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("lang_code", sa.Text(), nullable=True),
        sa.Column("version", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_index("idx_app_feedback_created", "app_feedback", ["created_datetime"], unique=False)
    op.create_table(
        "attribution_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attributions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result_digest", sa.Text(), nullable=True),
        sa.Column("job_id", sa.Text(), nullable=True),
        sa.Column("triggered_by", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_attribution_history_created_at", "attribution_history", ["created_at"], unique=False
    )
    op.create_index(
        "idx_attribution_history_snapshot",
        "attribution_history",
        ["source", "model", "source_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("kind = 'prejudge'"),
    )
    op.create_index(
        "idx_attribution_history_source_id",
        "attribution_history",
        ["source", "source_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "attributions",
        sa.Column("finding_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("prod_oid", sa.Text(), nullable=True),
        sa.Column("polarity", sa.Text(), nullable=True),
        sa.Column("sentiment_score", sa.Integer(), nullable=True),
        sa.Column("prejudge_stage", sa.Text(), nullable=True),
        sa.Column("l1_code", sa.Text(), nullable=True),
        sa.Column("l1_label", sa.Text(), nullable=True),
        sa.Column("l2_code", sa.Text(), nullable=True),
        sa.Column("l2_label", sa.Text(), nullable=True),
        sa.Column("conf_value", sa.Float(), nullable=True),
        sa.Column("conf_raw", sa.Float(), nullable=True),
        sa.Column("conf_tier", sa.Text(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("verdict_status", sa.Text(), nullable=True),
        sa.Column("verdict_by", sa.Text(), nullable=True),
        sa.Column("verdict_at", sa.Text(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("created_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_index("idx_attributions_l1", "attributions", ["l1_code"], unique=False)
    op.create_index("idx_attributions_l2", "attributions", ["l2_code"], unique=False)
    op.create_index("idx_attributions_polarity", "attributions", ["polarity"], unique=False)
    op.create_index(
        "idx_attributions_prejudge_stage", "attributions", ["prejudge_stage"], unique=False
    )
    op.create_index("idx_attributions_sentiment", "attributions", ["sentiment_score"], unique=False)
    op.create_index("idx_attributions_source", "attributions", ["source"], unique=False)
    op.create_index(
        "idx_attributions_source_id", "attributions", ["source", "source_id"], unique=False
    )
    op.create_index("idx_attributions_tier", "attributions", ["conf_tier"], unique=False)
    op.create_table(
        "batches",
        sa.Column("batch_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("original_name", sa.Text(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("inserted_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("batch_id"),
    )
    op.create_table(
        "conversations",
        sa.Column("session_oid", sa.Text(), nullable=False),
        sa.Column("bucket", sa.Text(), nullable=True),
        sa.Column("inbound_time", sa.Text(), nullable=True),
        sa.Column("trip_stage", sa.Text(), nullable=True),
        sa.Column("godate_diff", sa.Text(), nullable=True),
        sa.Column("msg_handler_bucket", sa.Text(), nullable=True),
        sa.Column("member_uuid", sa.Text(), nullable=True),
        sa.Column("order_oid", sa.Text(), nullable=True),
        sa.Column("order_mid", sa.Text(), nullable=True),
        sa.Column("order_create_time", sa.Text(), nullable=True),
        sa.Column("order_status_now", sa.Text(), nullable=True),
        sa.Column("order_lang", sa.Text(), nullable=True),
        sa.Column("go_date", sa.Text(), nullable=True),
        sa.Column("order_price", sa.Text(), nullable=True),
        sa.Column("order_profit", sa.Text(), nullable=True),
        sa.Column("order_create_source_code", sa.Text(), nullable=True),
        sa.Column("prod_oid", sa.Text(), nullable=True),
        sa.Column("product_name", sa.Text(), nullable=True),
        sa.Column("product_tz", sa.Text(), nullable=True),
        sa.Column("vertical", sa.Text(), nullable=True),
        sa.Column("bd_tag_cd", sa.Text(), nullable=True),
        sa.Column("bd_tag", sa.Text(), nullable=True),
        sa.Column("PM", sa.Text(), nullable=True),
        sa.Column("supplier_oid", sa.Text(), nullable=True),
        sa.Column("supplier_name", sa.Text(), nullable=True),
        sa.Column("cs_tag_oid", sa.Text(), nullable=True),
        sa.Column("cs_tag_name", sa.Text(), nullable=True),
        sa.Column("user_message_count", sa.Text(), nullable=True),
        sa.Column("conversation_full", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("session_oid"),
    )
    op.create_index("idx_conversations_bucket", "conversations", ["bucket"], unique=False)
    op.create_index(
        "idx_conversations_inbound_time", "conversations", ["inbound_time"], unique=False
    )
    op.create_index("idx_conversations_prod_oid", "conversations", ["prod_oid"], unique=False)
    op.create_index("idx_conversations_vertical", "conversations", ["vertical"], unique=False)
    op.create_table(
        "evidence_snapshot",
        sa.Column("order_oid", sa.BigInteger(), nullable=False),
        sa.Column("order_mid", sa.Text(), nullable=True),
        sa.Column("order_status", sa.Text(), nullable=True),
        sa.Column("price_pay", sa.Float(), nullable=True),
        sa.Column("lang_code", sa.Text(), nullable=True),
        sa.Column("crt_dt", sa.DateTime(timezone=True), nullable=True),
        sa.Column("prod_oid", sa.BigInteger(), nullable=True),
        sa.Column("prod_version", sa.BigInteger(), nullable=True),
        sa.Column("pkg_oid", sa.BigInteger(), nullable=True),
        sa.Column("item_oid", sa.BigInteger(), nullable=True),
        sa.Column("supplier_oid", sa.BigInteger(), nullable=True),
        sa.Column("lst_dt_go", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=True),
        sa.Column("pkg_name", sa.Text(), nullable=True),
        sa.Column("prod_desc", sa.Text(), nullable=True),
        sa.Column("supplier_name", sa.Text(), nullable=True),
        sa.Column("supplier_order_handler", sa.Text(), nullable=True),
        sa.Column("supplier_msg_handler", sa.Text(), nullable=True),
        sa.Column("product_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("product_desc_module", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("item_lang", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("item_setting", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("package_lang", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("package_setting", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("package_policy", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("package_module_setting", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("order_oid"),
    )
    op.create_index(
        "idx_evidence_snapshot_expires", "evidence_snapshot", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_evidence_snapshot_prod_oid", "evidence_snapshot", ["prod_oid"], unique=False
    )
    op.create_index(
        "idx_evidence_snapshot_supplier_oid", "evidence_snapshot", ["supplier_oid"], unique=False
    )
    op.create_table(
        "finding_notes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("finding_id", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_finding_notes_finding", "finding_notes", ["finding_id"], unique=False)
    op.create_table(
        "freshdesk_tickets",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("display_id", sa.Text(), nullable=True),
        sa.Column("ticket_type", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("attachments", sa.Text(), nullable=True),
        sa.Column("st_survey_rating", sa.Text(), nullable=True),
        sa.Column("product_id", sa.Text(), nullable=True),
        sa.Column("custom_field", sa.Text(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=True),
        sa.Column("status_name", sa.Text(), nullable=True),
        sa.Column("priority_name", sa.Text(), nullable=True),
        sa.Column("source_name", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.Column("requester_id", sa.Text(), nullable=True),
        sa.Column("parent_ticket_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_freshdesk_created_at", "freshdesk_tickets", ["created_at"], unique=False)
    op.create_index("idx_freshdesk_product_id", "freshdesk_tickets", ["product_id"], unique=False)
    op.create_table(
        "judge_rule_versions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("rule_code", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_code", "version", name="uq_judge_rule_code_version"),
    )
    op.create_index(
        "uq_judge_rule_active",
        "judge_rule_versions",
        ["rule_code"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "llm_usage",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("stage", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("source_id", sa.Text(), nullable=True),
        sa.Column("job_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_llm_usage_created_at", "llm_usage", ["created_at"], unique=False)
    op.create_index("idx_llm_usage_model", "llm_usage", ["model"], unique=False)
    op.create_index("idx_llm_usage_stage", "llm_usage", ["stage"], unique=False)
    op.create_table(
        "mixpanel_tracker",
        sa.Column("insert_id", sa.Text(), nullable=False),
        sa.Column("event", sa.Text(), nullable=True),
        sa.Column("time", sa.Text(), nullable=True),
        sa.Column("distinct_id", sa.Text(), nullable=True),
        sa.Column("feedback_signal", sa.Text(), nullable=True),
        sa.Column("negative_items", sa.Text(), nullable=True),
        sa.Column("display_style", sa.Text(), nullable=True),
        sa.Column("order_mid", sa.Text(), nullable=True),
        sa.Column("order_status", sa.Text(), nullable=True),
        sa.Column("order_master_mid", sa.Text(), nullable=True),
        sa.Column("is_marketplace", sa.Text(), nullable=True),
        sa.Column("prod_mid", sa.Text(), nullable=True),
        sa.Column("pkg_oid", sa.Text(), nullable=True),
        sa.Column("prod_city_code", sa.Text(), nullable=True),
        sa.Column("prod_country_code", sa.Text(), nullable=True),
        sa.Column("prod_info", sa.Text(), nullable=True),
        sa.Column("bd_tag", sa.Text(), nullable=True),
        sa.Column("msg_handler", sa.Text(), nullable=True),
        sa.Column("current_url", sa.Text(), nullable=True),
        sa.Column("platform", sa.Text(), nullable=True),
        sa.Column("mp_country_code", sa.Text(), nullable=True),
        sa.Column("os", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("insert_id"),
    )
    op.create_index("idx_mixpanel_time", "mixpanel_tracker", ["time"], unique=False)
    op.create_table(
        "prejudge_runs",
        sa.Column("job_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("rejudge", sa.Boolean(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=True),
        sa.Column("processed", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Integer(), nullable=True),
        sa.Column("failed", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.BigInteger(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("triggered_by", sa.Text(), nullable=True),
        sa.Column(
            "started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("log", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index("idx_prejudge_runs_started_at", "prejudge_runs", ["started_at"], unique=False)
    op.create_table(
        "prompt_debug_reviews",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("conversation", sa.Text(), nullable=False),
        sa.Column("ai_output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "corrections",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "confirmed",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), server_default="", nullable=False),
        sa.Column("prompt_version", sa.Text(), server_default="", nullable=False),
        sa.Column("model", sa.Text(), server_default="", nullable=False),
        sa.Column("reviewer", sa.Text(), server_default="", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_prompt_debug_reviews_created", "prompt_debug_reviews", ["created_at"], unique=False
    )
    op.create_table(
        "prompt_drafts",
        sa.Column("rule_code", sa.Text(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("base_version", sa.Integer(), nullable=False),
        sa.Column("updated_by", sa.Text(), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("rule_code"),
    )
    op.create_table(
        "prompt_sandbox_runs",
        sa.Column("run_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("item_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prompt_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("log", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("triggered_by", sa.Text(), nullable=True),
        sa.Column("job_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "versions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "drafts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("compare", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        "idx_prompt_sandbox_runs_created", "prompt_sandbox_runs", ["created_at"], unique=False
    )
    op.create_table(
        "reviews",
        sa.Column("rec_oid", sa.Text(), nullable=False),
        sa.Column("review_external_lst_oid", sa.Text(), nullable=True),
        sa.Column("create_date", sa.Text(), nullable=True),
        sa.Column("rec_title", sa.Text(), nullable=True),
        sa.Column("rec_desc", sa.Text(), nullable=True),
        sa.Column("rec_scores", sa.Text(), nullable=True),
        sa.Column("traveller_type", sa.Text(), nullable=True),
        sa.Column("lang_code", sa.Text(), nullable=True),
        sa.Column("sentiment", sa.Text(), nullable=True),
        sa.Column("free_tag", sa.Text(), nullable=True),
        sa.Column("member_uuid", sa.Text(), nullable=True),
        sa.Column("order_oid", sa.Text(), nullable=True),
        sa.Column("order_mid", sa.Text(), nullable=True),
        sa.Column("order_create_time", sa.Text(), nullable=True),
        sa.Column("order_lang", sa.Text(), nullable=True),
        sa.Column("go_date", sa.Text(), nullable=True),
        sa.Column("order_price", sa.Text(), nullable=True),
        sa.Column("order_profit", sa.Text(), nullable=True),
        sa.Column("order_create_source_code", sa.Text(), nullable=True),
        sa.Column("prod_oid", sa.Text(), nullable=True),
        sa.Column("pkg_oid", sa.Text(), nullable=True),
        sa.Column("product_name", sa.Text(), nullable=True),
        sa.Column("order_snap_json", sa.Text(), nullable=True),
        sa.Column("bd_tag_cd", sa.Text(), nullable=True),
        sa.Column("bd_tag", sa.Text(), nullable=True),
        sa.Column("supplier_oid", sa.Text(), nullable=True),
        sa.Column("supplier_name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("rec_oid"),
    )
    op.create_index("idx_reviews_create_date", "reviews", ["create_date"], unique=False)
    op.create_index("idx_reviews_prod_oid", "reviews", ["prod_oid"], unique=False)
    op.create_table(
        "settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """整批退回空庫（squash 前的歷史已不可回溯）。"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    op.drop_index("idx_reviews_prod_oid", table_name="reviews")
    op.drop_index("idx_reviews_create_date", table_name="reviews")
    op.drop_table("reviews")
    op.drop_index("idx_prompt_sandbox_runs_created", table_name="prompt_sandbox_runs")
    op.drop_table("prompt_sandbox_runs")
    op.drop_table("prompt_drafts")
    op.drop_index("idx_prompt_debug_reviews_created", table_name="prompt_debug_reviews")
    op.drop_table("prompt_debug_reviews")
    op.drop_index("idx_prejudge_runs_started_at", table_name="prejudge_runs")
    op.drop_table("prejudge_runs")
    op.drop_index("idx_mixpanel_time", table_name="mixpanel_tracker")
    op.drop_table("mixpanel_tracker")
    op.drop_index("idx_llm_usage_stage", table_name="llm_usage")
    op.drop_index("idx_llm_usage_model", table_name="llm_usage")
    op.drop_index("idx_llm_usage_created_at", table_name="llm_usage")
    op.drop_table("llm_usage")
    op.drop_index(
        "uq_judge_rule_active",
        table_name="judge_rule_versions",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_table("judge_rule_versions")
    op.drop_index("idx_freshdesk_product_id", table_name="freshdesk_tickets")
    op.drop_index("idx_freshdesk_created_at", table_name="freshdesk_tickets")
    op.drop_table("freshdesk_tickets")
    op.drop_index("idx_finding_notes_finding", table_name="finding_notes")
    op.drop_table("finding_notes")
    op.drop_index("idx_evidence_snapshot_supplier_oid", table_name="evidence_snapshot")
    op.drop_index("idx_evidence_snapshot_prod_oid", table_name="evidence_snapshot")
    op.drop_index("idx_evidence_snapshot_expires", table_name="evidence_snapshot")
    op.drop_table("evidence_snapshot")
    op.drop_index("idx_conversations_vertical", table_name="conversations")
    op.drop_index("idx_conversations_prod_oid", table_name="conversations")
    op.drop_index("idx_conversations_inbound_time", table_name="conversations")
    op.drop_index("idx_conversations_bucket", table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("batches")
    op.drop_index("idx_attributions_tier", table_name="attributions")
    op.drop_index("idx_attributions_source_id", table_name="attributions")
    op.drop_index("idx_attributions_source", table_name="attributions")
    op.drop_index("idx_attributions_sentiment", table_name="attributions")
    op.drop_index("idx_attributions_prejudge_stage", table_name="attributions")
    op.drop_index("idx_attributions_polarity", table_name="attributions")
    op.drop_index("idx_attributions_l2", table_name="attributions")
    op.drop_index("idx_attributions_l1", table_name="attributions")
    op.drop_table("attributions")
    op.drop_index("idx_attribution_history_source_id", table_name="attribution_history")
    op.drop_index(
        "idx_attribution_history_snapshot",
        table_name="attribution_history",
        postgresql_where=sa.text("kind = 'prejudge'"),
    )
    op.drop_index("idx_attribution_history_created_at", table_name="attribution_history")
    op.drop_table("attribution_history")
    op.drop_index("idx_app_feedback_created", table_name="app_feedback")
    op.drop_table("app_feedback")
    # ### end Alembic commands ###
