"""冗餘稽核第一批：is_ 前綴、審計欄型別、NULL 表示法正規化、刪可推導欄

逐欄稽核（140 欄）後對抗式驗證確認的 10 項中，本支處理**低風險且判準明確**的 4 項；
其餘 5 項涉及較大改動面或產品判斷，另案排期。

**① `prejudge_run_tbl.rejudge` → `is_rejudge`**
規範第一章：「flag用途的欄名，請都用 `is_` 開頭,資料格式開boolean」。全庫 boolean 欄唯獨這個
沒有前綴（同庫的 `is_auto_accepted` / `is_primary` / `is_active` 都有）。以 `key="rejudge"`
保留 Python 端與 wire 名稱，僅 DB 欄名變更。

**② `attribution_event_lst.author` → varchar(36)**
存的是 user email＝行為人（審計語義），規範要求審計欄 `varchar(36)`；同表 `create_user` 已是。
實測 max(length)=20，轉型不截斷。

**③ `attribution_event_lst.attribution_snapshot` 的 NULL 表示法正規化**
同一個「沒有快照」狀態存在兩種編碼：360 筆 failure 列（07-14~07-31）與 1 筆 note 列存 jsonb
純量 `'null'`，而 08-03 之後的列存 SQL NULL。導致 `count(欄)` 比真實非空多算 361 列（2.55%），
且 `IS NOT NULL` 會撈到 failure 列——與欄註解「僅 kind=prejudge 有值」在 SQL 層自相矛盾。
寫入端目前已正確，本支只正規化歷史列。
（API 層無感：psycopg2 把 jsonb `'null'` 也解成 Python None，失真只在 SQL 分析面。）

**④ 刪 `llm_usage_lst.total_tokens`**
實測 58,537 / 58,537 列滿足 `total_tokens = prompt_tokens + completion_tokens`，零反例、三欄皆無
NULL。聚合端改為 `sum(prompt_tokens + completion_tokens)`。
⚠️ **勿誤刪 `prejudge_run_tbl.total_tokens`**——那是 run 級累計（BigInteger），語義不同。

Revision ID: a3f6520ce8d1
Revises: f1b78d3a95c2
Create Date: 2026-08-04

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a3f6520ce8d1"
down_revision: str | Sequence[str] | None = "f1b78d3a95c2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_UPGRADE: tuple[str, ...] = (
    # ① boolean flag 一律 is_ 前綴
    "ALTER TABLE prejudge_run_tbl RENAME COLUMN rejudge TO is_rejudge",
    "COMMENT ON COLUMN prejudge_run_tbl.is_rejudge IS '標的先前已有初判結果 → 本次為重新初判'",
    # ② 審計語義欄對齊 varchar(36)
    "ALTER TABLE attribution_event_lst ALTER COLUMN author TYPE varchar(36)",
    # ③ jsonb 純量 'null' → SQL NULL（同一狀態只留一種編碼）
    "UPDATE attribution_event_lst SET attribution_snapshot = NULL "
    "WHERE attribution_snapshot IS NOT NULL AND jsonb_typeof(attribution_snapshot) = 'null'",
    # ④ 可完全推導的欄退場——走**重建**而非 DROP COLUMN：
    #    `information_schema.ordinal_position` 就是 `attnum`，DROP 後會留下編號空洞而不重新編號，
    #    於是「跑鏈的庫」與「create_all 的新庫」欄序又對不上（cost_usd 一邊 9、一邊 8）。
    #    重建順帶把 attnum 壓實。
    # ── llm_usage_lst 重建（欄序照 tables.py，PK 置首）──
    "CREATE TABLE llm_usage_lst__rebuild ( llm_usage_oid INTEGER GENERATED BY DEFAULT AS IDENTITY, stage TEXT, model TEXT NOT NULL, prompt_tokens INTEGER, completion_tokens INTEGER, reasoning_tokens INTEGER, cached_tokens INTEGER, cost_usd FLOAT, feedback_source_code TEXT, job_id TEXT, create_date TIMESTAMP WITH TIME ZONE DEFAULT now(), create_user VARCHAR(36), PRIMARY KEY (llm_usage_oid) )",
    "INSERT INTO llm_usage_lst__rebuild (llm_usage_oid, stage, model, prompt_tokens, completion_tokens, reasoning_tokens, cached_tokens, cost_usd, feedback_source_code, job_id, create_date, create_user) OVERRIDING SYSTEM VALUE SELECT llm_usage_oid, stage, model, prompt_tokens, completion_tokens, reasoning_tokens, cached_tokens, cost_usd, feedback_source_code, job_id, create_date, create_user FROM llm_usage_lst",
    "DROP TABLE llm_usage_lst",
    "ALTER TABLE llm_usage_lst__rebuild RENAME TO llm_usage_lst",
    "ALTER TABLE llm_usage_lst RENAME CONSTRAINT llm_usage_lst__rebuild_pkey TO llm_usage_lst_pkey",
    "CREATE INDEX idx_llm_usage_lst_stage ON llm_usage_lst (stage)",
    "CREATE INDEX idx_llm_usage_lst_model ON llm_usage_lst (model)",
    "CREATE INDEX idx_llm_usage_lst_create_date ON llm_usage_lst (create_date)",
    "COMMENT ON TABLE llm_usage_lst IS 'AI 使用紀錄（per-call：每次真實 LLM 呼叫落一列），供成本 dashboard 多維度聚合。唯一寫入點＝llm.client 的 usage recorder（批次走 buffer 批量寫、單次即時寫）'",
    "COMMENT ON COLUMN llm_usage_lst.llm_usage_oid IS '流水號主鍵（serial）'",
    "COMMENT ON COLUMN llm_usage_lst.stage IS '呼叫階段：polarity / C-1~C-6 / prompt_debug / prompt_revise…'",
    "COMMENT ON COLUMN llm_usage_lst.model IS '實際使用的模型（cfg.model）'",
    "COMMENT ON COLUMN llm_usage_lst.prompt_tokens IS '輸入 token 數'",
    "COMMENT ON COLUMN llm_usage_lst.completion_tokens IS '輸出 token 數（reasoning model 下已含 reasoning_tokens）'",
    "COMMENT ON COLUMN llm_usage_lst.reasoning_tokens IS 'completion 中屬 reasoning 的部分（reasoning_effort 產出；供量測降檔位的空間）'",
    "COMMENT ON COLUMN llm_usage_lst.cached_tokens IS 'prompt 中命中 prompt cache 的 token 數（折扣計價）'",
    "COMMENT ON COLUMN llm_usage_lst.cost_usd IS '本次呼叫費用（pricing.cost_usd 換算，含 cache 折扣與 service tier）'",
    "COMMENT ON COLUMN llm_usage_lst.feedback_source_code IS '反饋來源 code（reviews…）；ad-hoc 呼叫為空'",
    "COMMENT ON COLUMN llm_usage_lst.job_id IS '所屬批次任務 id；單次呼叫為空'",
    "COMMENT ON COLUMN llm_usage_lst.create_date IS '呼叫時間'",
    "COMMENT ON COLUMN llm_usage_lst.create_user IS '建立者（user email 或 system:* 標記）'",
    "SELECT setval(pg_get_serial_sequence('llm_usage_lst', 'llm_usage_oid'), GREATEST(COALESCE((SELECT max(llm_usage_oid) FROM llm_usage_lst), 0), 1))",
)


def upgrade() -> None:
    """套用第一批稽核修正。"""
    for stmt in _UPGRADE:
        op.execute(stmt)


def downgrade() -> None:
    """還原結構；③ 的 NULL 表示法不回填（兩種編碼在語義上等價，回填無意義）。"""
    op.add_column("llm_usage_lst", sa.Column("total_tokens", sa.Integer(), nullable=True))
    op.execute("UPDATE llm_usage_lst SET total_tokens = prompt_tokens + completion_tokens")
    op.execute("ALTER TABLE attribution_event_lst ALTER COLUMN author TYPE text")
    op.execute("ALTER TABLE prejudge_run_tbl RENAME COLUMN is_rejudge TO rejudge")
