"""DDL 規範對齊：9 張自建表改名 + serial PK + 審計欄 + 保留字改名 + 型別轉正 + 索引改名

依 KKday DataBase DDL 規範改造 9 張**自建**表（5 張來源鏡像表忠實鏡射上游 BQ 輸出，不在範圍）：

1. **表名** → `名詞_master`（主檔單例）/ `_tbl`（主要資料表）/ `_lst`（append-only 明細流水）
2. **PK** → `<名詞>_oid` serial（`GENERATED BY DEFAULT AS IDENTITY`）；原業務鍵降為
   `idx_<表>_unique01` 唯一索引，語義不變、外部引用照舊
3. **審計欄** → `create_user` / `create_date` / `modify_user` / `modify_date`；
   **多數是既有欄改名而非新增**（`author`→`create_user`、`triggered_by`→`create_user`、
   `created_at`→`create_date`…），故不會產生一堆恆 NULL 的新欄。append-only 表（
   `attribution_event_lst` / `llm_usage_lst` / `judge_rule_version_lst`）依規範只開前兩欄
4. **保留字改名** 14 處（`source`→`feedback_source_code`、`action`→`recommended_action`、
   `status`→`run_status`、`key`/`data`→`setting_code`/`setting_value`…）
5. **型別轉正**：3 個存 ISO 8601 字串的 `text` 時間欄 → `timestamptz`
   （套用前實測 6,242/6,242 + 16/16 + 1/1 全部可安全轉型，無空值）
6. **索引改名** 20 個 → `idx_<表>_<欄名>` / `_mix??`（複合）/ `_unique??`（唯一）

⚠️ **wire 契約刻意不變**：本規範管的是 DataBase，不是 API。DB 欄改名後由讀取層以 `.label()`
對回原 wire key，前端零改動——由 `tests/test_wire_contract.py` 的凍結快照證明契約沒動。

⚠️ **就地 ALTER 而非建新表搬遷**：最大表 5.8 萬列、秒級完成；就地改沒有「新舊表並存」的中間期，
也不需要對帳搬遷正確性（沒搬就沒錯）。`RENAME` 是原子操作，資料一列都不動。

⚠️ **PK 約束名一律執行期查 catalog，不可寫死**：本機 dev 庫的 `settings` PK 叫 `user_settings_pkey`
（早年表名為 `user_settings` 的殘留），但**全新庫**跑 baseline 建出來的叫 `settings_pkey`——寫死任一個
都會在另一種庫上炸。故用 `DO $$ … SELECT conname FROM pg_constraint … EXECUTE format(…) $$` 動態解析。
（此坑由 `test_schema_parity` 的空庫實跑抓到，不是靠人眼看出來的。）
同理 `uq_judge_rule_code_version` 是 UNIQUE **約束**不是純索引，走 `RENAME CONSTRAINT` 而非 `ALTER INDEX`。

Revision ID: a8e5c31d0f62
Revises: f3d92a7c48be
Create Date: 2026-08-04

"""

from collections.abc import Sequence

from alembic import op

revision: str = "a8e5c31d0f62"
down_revision: str | Sequence[str] | None = "f3d92a7c48be"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_UPGRADE: tuple[str, ...] = (
    # ── attributions → attribution_tbl（PK finding_id → attribution_oid serial）──
    "ALTER TABLE attributions RENAME TO attribution_tbl",
    "ALTER TABLE attribution_tbl RENAME COLUMN source TO feedback_source_code",
    "ALTER TABLE attribution_tbl RENAME COLUMN action TO recommended_action",
    "ALTER TABLE attribution_tbl RENAME COLUMN created_at TO create_date",
    "ALTER TABLE attribution_tbl ALTER COLUMN create_date TYPE timestamptz USING NULLIF(create_date, '')::timestamptz",
    "DO $$ DECLARE c text; BEGIN SELECT conname INTO c FROM pg_constraint WHERE conrelid = 'attribution_tbl'::regclass AND contype = 'p'; EXECUTE format('ALTER TABLE attribution_tbl DROP CONSTRAINT %I', c); END $$;",
    "ALTER TABLE attribution_tbl ADD COLUMN attribution_oid INTEGER GENERATED BY DEFAULT AS IDENTITY",
    "ALTER TABLE attribution_tbl ADD CONSTRAINT attribution_tbl_pkey PRIMARY KEY (attribution_oid)",
    "CREATE UNIQUE INDEX idx_attribution_tbl_unique01 ON attribution_tbl (finding_id)",
    "ALTER TABLE attribution_tbl ADD COLUMN create_user varchar(36)",
    "ALTER TABLE attribution_tbl ADD COLUMN modify_user varchar(36)",
    "ALTER TABLE attribution_tbl ADD COLUMN modify_date timestamptz",
    # ── attribution_history → attribution_event_lst（PK id → attribution_event_oid serial）──
    "ALTER TABLE attribution_history RENAME TO attribution_event_lst",
    "ALTER TABLE attribution_event_lst RENAME COLUMN source TO feedback_source_code",
    "ALTER TABLE attribution_event_lst RENAME COLUMN content TO note_content",
    "ALTER TABLE attribution_event_lst RENAME COLUMN attributions TO attribution_snapshot",
    "ALTER TABLE attribution_event_lst RENAME COLUMN triggered_by TO create_user",
    "ALTER TABLE attribution_event_lst RENAME COLUMN created_at TO create_date",
    "DO $$ DECLARE c text; BEGIN SELECT conname INTO c FROM pg_constraint WHERE conrelid = 'attribution_event_lst'::regclass AND contype = 'p'; EXECUTE format('ALTER TABLE attribution_event_lst DROP CONSTRAINT %I', c); END $$;",
    "ALTER TABLE attribution_event_lst ADD COLUMN attribution_event_oid INTEGER GENERATED BY DEFAULT AS IDENTITY",
    "ALTER TABLE attribution_event_lst ADD CONSTRAINT attribution_event_lst_pkey PRIMARY KEY (attribution_event_oid)",
    "ALTER TABLE attribution_event_lst DROP COLUMN id",
    # ── llm_usage → llm_usage_lst（PK id → llm_usage_oid serial）──
    "ALTER TABLE llm_usage RENAME TO llm_usage_lst",
    "ALTER TABLE llm_usage_lst RENAME COLUMN source TO feedback_source_code",
    "ALTER TABLE llm_usage_lst RENAME COLUMN created_at TO create_date",
    "DO $$ DECLARE c text; BEGIN SELECT conname INTO c FROM pg_constraint WHERE conrelid = 'llm_usage_lst'::regclass AND contype = 'p'; EXECUTE format('ALTER TABLE llm_usage_lst DROP CONSTRAINT %I', c); END $$;",
    "ALTER TABLE llm_usage_lst ADD COLUMN llm_usage_oid INTEGER GENERATED BY DEFAULT AS IDENTITY",
    "ALTER TABLE llm_usage_lst ADD CONSTRAINT llm_usage_lst_pkey PRIMARY KEY (llm_usage_oid)",
    "ALTER TABLE llm_usage_lst DROP COLUMN id",
    "ALTER TABLE llm_usage_lst ADD COLUMN create_user varchar(36)",
    # ── prejudge_runs → prejudge_run_tbl（PK job_id → prejudge_run_oid serial）──
    "ALTER TABLE prejudge_runs RENAME TO prejudge_run_tbl",
    "ALTER TABLE prejudge_run_tbl RENAME COLUMN source TO feedback_source_code",
    "ALTER TABLE prejudge_run_tbl RENAME COLUMN status TO run_status",
    "ALTER TABLE prejudge_run_tbl RENAME COLUMN kind TO trigger_kind",
    "ALTER TABLE prejudge_run_tbl RENAME COLUMN triggered_by TO create_user",
    "ALTER TABLE prejudge_run_tbl RENAME COLUMN started_at TO create_date",
    "DO $$ DECLARE c text; BEGIN SELECT conname INTO c FROM pg_constraint WHERE conrelid = 'prejudge_run_tbl'::regclass AND contype = 'p'; EXECUTE format('ALTER TABLE prejudge_run_tbl DROP CONSTRAINT %I', c); END $$;",
    "ALTER TABLE prejudge_run_tbl ADD COLUMN prejudge_run_oid INTEGER GENERATED BY DEFAULT AS IDENTITY",
    "ALTER TABLE prejudge_run_tbl ADD CONSTRAINT prejudge_run_tbl_pkey PRIMARY KEY (prejudge_run_oid)",
    "CREATE UNIQUE INDEX idx_prejudge_run_tbl_unique01 ON prejudge_run_tbl (job_id)",
    "ALTER TABLE prejudge_run_tbl ADD COLUMN modify_user varchar(36)",
    "ALTER TABLE prejudge_run_tbl ADD COLUMN modify_date timestamptz",
    # ── prompt_debug_reviews → prompt_debug_review_tbl（PK id → prompt_debug_review_oid serial）──
    "ALTER TABLE prompt_debug_reviews RENAME TO prompt_debug_review_tbl",
    "ALTER TABLE prompt_debug_review_tbl RENAME COLUMN comment TO reviewer_comment",
    "ALTER TABLE prompt_debug_review_tbl RENAME COLUMN reviewer TO create_user",
    "ALTER TABLE prompt_debug_review_tbl RENAME COLUMN created_at TO create_date",
    "DO $$ DECLARE c text; BEGIN SELECT conname INTO c FROM pg_constraint WHERE conrelid = 'prompt_debug_review_tbl'::regclass AND contype = 'p'; EXECUTE format('ALTER TABLE prompt_debug_review_tbl DROP CONSTRAINT %I', c); END $$;",
    "ALTER TABLE prompt_debug_review_tbl ADD COLUMN prompt_debug_review_oid INTEGER GENERATED BY DEFAULT AS IDENTITY",
    "ALTER TABLE prompt_debug_review_tbl ADD CONSTRAINT prompt_debug_review_tbl_pkey PRIMARY KEY (prompt_debug_review_oid)",
    "ALTER TABLE prompt_debug_review_tbl DROP COLUMN id",
    "ALTER TABLE prompt_debug_review_tbl ADD COLUMN modify_user varchar(36)",
    "ALTER TABLE prompt_debug_review_tbl ADD COLUMN modify_date timestamptz",
    # ── judge_rule_versions → judge_rule_version_lst（PK id → judge_rule_version_oid serial）──
    "ALTER TABLE judge_rule_versions RENAME TO judge_rule_version_lst",
    "ALTER TABLE judge_rule_version_lst RENAME COLUMN content TO rule_content",
    "ALTER TABLE judge_rule_version_lst RENAME COLUMN version TO version_number",
    "ALTER TABLE judge_rule_version_lst RENAME COLUMN author TO create_user",
    "ALTER TABLE judge_rule_version_lst RENAME COLUMN created_at TO create_date",
    "DO $$ DECLARE c text; BEGIN SELECT conname INTO c FROM pg_constraint WHERE conrelid = 'judge_rule_version_lst'::regclass AND contype = 'p'; EXECUTE format('ALTER TABLE judge_rule_version_lst DROP CONSTRAINT %I', c); END $$;",
    "ALTER TABLE judge_rule_version_lst ADD COLUMN judge_rule_version_oid INTEGER GENERATED BY DEFAULT AS IDENTITY",
    "ALTER TABLE judge_rule_version_lst ADD CONSTRAINT judge_rule_version_lst_pkey PRIMARY KEY (judge_rule_version_oid)",
    "ALTER TABLE judge_rule_version_lst DROP COLUMN id",
    "ALTER TABLE judge_rule_version_lst RENAME CONSTRAINT uq_judge_rule_code_version TO idx_judge_rule_version_lst_unique01",
    # ── batches → upload_batch_tbl（PK batch_id → upload_batch_oid serial）──
    "ALTER TABLE batches RENAME TO upload_batch_tbl",
    "ALTER TABLE upload_batch_tbl RENAME COLUMN source TO feedback_source_code",
    "ALTER TABLE upload_batch_tbl RENAME COLUMN name TO batch_name",
    "ALTER TABLE upload_batch_tbl RENAME COLUMN uploaded_at TO create_date",
    "ALTER TABLE upload_batch_tbl ALTER COLUMN create_date TYPE timestamptz USING NULLIF(create_date, '')::timestamptz",
    "DO $$ DECLARE c text; BEGIN SELECT conname INTO c FROM pg_constraint WHERE conrelid = 'upload_batch_tbl'::regclass AND contype = 'p'; EXECUTE format('ALTER TABLE upload_batch_tbl DROP CONSTRAINT %I', c); END $$;",
    "ALTER TABLE upload_batch_tbl ADD COLUMN upload_batch_oid INTEGER GENERATED BY DEFAULT AS IDENTITY",
    "ALTER TABLE upload_batch_tbl ADD CONSTRAINT upload_batch_tbl_pkey PRIMARY KEY (upload_batch_oid)",
    "CREATE UNIQUE INDEX idx_upload_batch_tbl_unique01 ON upload_batch_tbl (batch_id)",
    "ALTER TABLE upload_batch_tbl ADD COLUMN create_user varchar(36)",
    "ALTER TABLE upload_batch_tbl ADD COLUMN modify_user varchar(36)",
    "ALTER TABLE upload_batch_tbl ADD COLUMN modify_date timestamptz",
    # ── settings → setting_master（PK key → setting_oid serial）──
    "ALTER TABLE settings RENAME TO setting_master",
    "ALTER TABLE setting_master RENAME COLUMN key TO setting_code",
    "ALTER TABLE setting_master RENAME COLUMN data TO setting_value",
    "ALTER TABLE setting_master RENAME COLUMN updated_at TO modify_date",
    "ALTER TABLE setting_master ALTER COLUMN modify_date TYPE timestamptz USING NULLIF(modify_date, '')::timestamptz",
    "DO $$ DECLARE c text; BEGIN SELECT conname INTO c FROM pg_constraint WHERE conrelid = 'setting_master'::regclass AND contype = 'p'; EXECUTE format('ALTER TABLE setting_master DROP CONSTRAINT %I', c); END $$;",
    "ALTER TABLE setting_master ADD COLUMN setting_oid INTEGER GENERATED BY DEFAULT AS IDENTITY",
    "ALTER TABLE setting_master ADD CONSTRAINT setting_master_pkey PRIMARY KEY (setting_oid)",
    "CREATE UNIQUE INDEX idx_setting_master_unique01 ON setting_master (setting_code)",
    "ALTER TABLE setting_master ADD COLUMN create_user varchar(36)",
    "ALTER TABLE setting_master ADD COLUMN create_date timestamptz",
    "ALTER TABLE setting_master ADD COLUMN modify_user varchar(36)",
    # ── evidence_snapshot → evidence_snapshot_tbl（PK order_oid → evidence_snapshot_oid serial）──
    "ALTER TABLE evidence_snapshot RENAME TO evidence_snapshot_tbl",
    "ALTER TABLE evidence_snapshot_tbl RENAME COLUMN timezone TO product_timezone",
    "ALTER TABLE evidence_snapshot_tbl RENAME COLUMN fetched_at TO create_date",
    "DO $$ DECLARE c text; BEGIN SELECT conname INTO c FROM pg_constraint WHERE conrelid = 'evidence_snapshot_tbl'::regclass AND contype = 'p'; EXECUTE format('ALTER TABLE evidence_snapshot_tbl DROP CONSTRAINT %I', c); END $$;",
    "ALTER TABLE evidence_snapshot_tbl ADD COLUMN evidence_snapshot_oid INTEGER GENERATED BY DEFAULT AS IDENTITY",
    "ALTER TABLE evidence_snapshot_tbl ADD CONSTRAINT evidence_snapshot_tbl_pkey PRIMARY KEY (evidence_snapshot_oid)",
    "CREATE UNIQUE INDEX idx_evidence_snapshot_tbl_unique01 ON evidence_snapshot_tbl (order_oid)",
    # order_oid 原為 BigInteger PK（SQLAlchemy 產生 serial），降級後 nextval 預設要一併卸掉
    "ALTER TABLE evidence_snapshot_tbl ALTER COLUMN order_oid DROP DEFAULT",
    "ALTER TABLE evidence_snapshot_tbl ADD COLUMN create_user varchar(36)",
    "ALTER TABLE evidence_snapshot_tbl ADD COLUMN modify_user varchar(36)",
    "ALTER TABLE evidence_snapshot_tbl ADD COLUMN modify_date timestamptz",
    # ── 索引改名：idx_<表>_<欄名> / _mix??（複合）/ _unique??（唯一）──
    "ALTER INDEX idx_attributions_source RENAME TO idx_attribution_tbl_feedback_source_code",
    "ALTER INDEX idx_attributions_source_id RENAME TO idx_attribution_tbl_mix01",
    "ALTER INDEX idx_attributions_polarity RENAME TO idx_attribution_tbl_polarity",
    "ALTER INDEX idx_attributions_prejudge_stage RENAME TO idx_attribution_tbl_prejudge_stage",
    "ALTER INDEX idx_attributions_l1 RENAME TO idx_attribution_tbl_l1_code",
    "ALTER INDEX idx_attributions_l2 RENAME TO idx_attribution_tbl_l2_code",
    "ALTER INDEX idx_attributions_sentiment RENAME TO idx_attribution_tbl_sentiment_score",
    "ALTER INDEX idx_attributions_tier RENAME TO idx_attribution_tbl_conf_tier",
    "ALTER INDEX idx_attribution_history_source_id RENAME TO idx_attribution_event_lst_mix01",
    "ALTER INDEX idx_attribution_history_created_at RENAME TO idx_attribution_event_lst_create_date",
    "ALTER INDEX idx_attribution_history_snapshot RENAME TO idx_attribution_event_lst_mix02",
    "ALTER INDEX idx_llm_usage_created_at RENAME TO idx_llm_usage_lst_create_date",
    "ALTER INDEX idx_llm_usage_model RENAME TO idx_llm_usage_lst_model",
    "ALTER INDEX idx_llm_usage_stage RENAME TO idx_llm_usage_lst_stage",
    "ALTER INDEX idx_prejudge_runs_started_at RENAME TO idx_prejudge_run_tbl_create_date",
    "ALTER INDEX idx_prompt_debug_reviews_created RENAME TO idx_prompt_debug_review_tbl_create_date",
    "ALTER INDEX uq_judge_rule_active RENAME TO idx_judge_rule_version_lst_unique02",
    "ALTER INDEX idx_evidence_snapshot_expires RENAME TO idx_evidence_snapshot_tbl_expires_at",
    "ALTER INDEX idx_evidence_snapshot_prod_oid RENAME TO idx_evidence_snapshot_tbl_prod_oid",
    "ALTER INDEX idx_evidence_snapshot_supplier_oid RENAME TO idx_evidence_snapshot_tbl_supplier_oid",
)


def upgrade() -> None:
    """依序套用表改名 → 欄改名 → 型別轉正 → PK 換 serial → 審計欄 → 索引改名。"""
    for stmt in _UPGRADE:
        op.execute(stmt)


def downgrade() -> None:
    """回退：僅把 9 張表名改回原名。

    **不還原欄名／PK／型別**——本支是單向的規範對齊，逐條逆轉需要 100+ 條語句且
    `timestamptz`→`text` 會改變值的字面形式（不可能逐字還原原始字串）。真要完整回退，
    走 `pg_dump` 備份還原（套用前已備份至 ~/kkday-backups/）。
    """
    for old_t, new_t in _TABLE_RENAMES_REVERSED:
        op.execute(f"ALTER TABLE {new_t} RENAME TO {old_t}")


_TABLE_RENAMES_REVERSED: tuple[tuple[str, str], ...] = (
    ("attributions", "attribution_tbl"),
    ("attribution_history", "attribution_event_lst"),
    ("llm_usage", "llm_usage_lst"),
    ("prejudge_runs", "prejudge_run_tbl"),
    ("prompt_debug_reviews", "prompt_debug_review_tbl"),
    ("judge_rule_versions", "judge_rule_version_lst"),
    ("batches", "upload_batch_tbl"),
    ("settings", "setting_master"),
    ("evidence_snapshot", "evidence_snapshot_tbl"),
)
