"""反饋備註獨立表 + note_type 值域第四軸；kind='note' 事件退役

## 為什麼備註不留在事件表

`attribution_event_lst.params` 承載的是「那個事件當下發生了什麼」的**凍結快照**——`correction` 的
`changed`、`suggestion` 的 `batch_id`，寫完就不再被查詢的死指標。而備註要能按**面向**撈（工作台每
開一次就查一次）、按反饋算數量（列表徽記），那是**活的查詢鍵**。活查詢鍵埋進凍結 JSONB 就永遠
無法建索引、無法對 note_type 做參照約束、每次查詢都要走 JSONB path。兩者生命週期不同，分表。

呈現層仍是**單一時間軸**：`list_attribution_history` 在回傳時把備註併進事件序列，前端只吃一個來源。

## 為什麼綁面向而不綁 attribution_oid

歸因級備註曾經存在也曾經死過——`finding_notes` 表 2026-08-04 隨 `b2f47c9e15a3` 退役，死因是
「8 列中 6 列已是孤兒」：它綁流水號，而 AI 託管反饋重判時是 DELETE 全部 + INSERT 新列。
改綁 `(source, source_id, l1_code, l2_code)` 之後，面向消失時備註仍自我描述（「這則反饋在
『餐飲品質』上，某人曾說過 X」），是有意義的歷史而不是資料垃圾。

## 既有 kind='note' 事件的處理

**搬遷後刪除**，不留在原表製造兩處真相。dev 庫實跑搬了 1 筆（型別一律落 `internal`＝內部說明，
因為舊事件沒有互動類型這個維度，事後也無從推斷）。搬遷是無條件執行的——空集合時它就是個 no-op，
但有資料時漏搬就是永久遺失人手寫的內容。

Revision ID: b7d419e0c852
Revises: a3e58d21c9f4
Create Date: 2026-08-07
"""

import json
from pathlib import Path

import sqlalchemy as sa

from alembic import op

revision = "b7d419e0c852"
down_revision = "a3e58d21c9f4"
branch_labels = None
depends_on = None

_SEED = Path(__file__).resolve().parents[3] / "config" / "ai_judge" / "attribution_dimension.json"


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS attribution_note_lst (
            attribution_note_oid  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            feedback_source_code  text NOT NULL,
            source_id             text NOT NULL,
            l1_code               text,
            l2_code               text,
            note_type             text NOT NULL,
            content               text NOT NULL,
            create_user           varchar(255),
            create_date           timestamptz DEFAULT now()
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_attribution_note_lst_mix01 "
        "ON attribution_note_lst (feedback_source_code, source_id, create_date)"
    )

    # 欄註解（test_schema_parity 逐字比對，須與 tables.py 完全一致）
    comments = {
        "attribution_note_oid": "流水號主鍵（serial）",
        "feedback_source_code": "反饋來源 code（reviews…）",
        "source_id": "該來源的特徵 id（反饋級鍵）",
        "l1_code": (
            "歸因域機器碼；與 l2_code 皆 NULL＝整則備註，皆有值＝面向備註。"
            "**綁面向而非 attribution_oid**：歸因列每次重新初判都整批換掉（先刪後插），綁流水號的"
            "東西一重判就成孤兒——2026-08-04 退役的 finding_notes 表 8 列裡有 6 列正是這樣死的。"
            "面向鍵跨重判穩定，而且即使該面向之後消失，備註本身仍自我描述（讀得懂當初在講什麼）"
        ),
        "l2_code": "歸因面向機器碼（同 l1_code 的說明）",
        "note_type": (
            "互動類型機器碼；值域＝attribution_dimension_master 的 note_type 軸（業務可維護）"
        ),
        "content": "備註內容",
        "create_user": "留下這則備註的人（無 SSO 時為 system）",
        "create_date": "建立時間",
    }
    for col, text in comments.items():
        op.execute(f"COMMENT ON COLUMN attribution_note_lst.{col} IS {_q(text)}")
    op.execute(
        "COMMENT ON TABLE attribution_note_lst IS "
        + _q(
            "反饋備註（append-only，不剪枝）。l1_code/l2_code 皆 NULL＝整則備註、皆有值＝面向備註。"
            "**不與 attribution_event_lst 共用**：那張表的 params 承載的是「事件當下發生了什麼」的凍結"
            "快照（寫完就不再查詢的死指標），而備註的面向鍵是活的查詢鍵（每次開工作台都要按面向撈、"
            "列表要算數量）——活查詢鍵埋進凍結 JSONB 就永遠無法建索引、無法對 note_type 做參照約束"
        )
    )

    # note_type 值域第四軸（seed 檔為默認值，DB 為 live；已存在的 code 不覆蓋）
    seed = json.loads(_SEED.read_text(encoding="utf-8"))
    for i, item in enumerate(seed.get("note_type", {}).get("items", [])):
        op.execute(
            sa.text(
                "INSERT INTO attribution_dimension_master "
                "(dimension_code, item_code, item_label, item_desc, sort_order, create_user) "
                "VALUES ('note_type', :c, :l, :d, :s, 'system') "
                "ON CONFLICT (dimension_code, item_code) DO NOTHING"
            ).bindparams(c=item["code"], l=item["label"], d=item.get("desc"), s=i)
        )

    # 既有 kind='note' 事件搬進新表後刪除——不留在原表製造兩處真相。
    # 舊事件沒有互動類型這個維度，一律落 'internal'（內部說明），事後無從推斷更精確的值。
    op.execute(
        """
        INSERT INTO attribution_note_lst
            (feedback_source_code, source_id, note_type, content, create_user, create_date)
        SELECT feedback_source_code, source_id, 'internal', note_content,
               COALESCE(author, 'system'), create_date
        FROM attribution_event_lst
        WHERE kind = 'note' AND note_content IS NOT NULL AND btrim(note_content) <> ''
        """
    )
    op.execute("DELETE FROM attribution_event_lst WHERE kind = 'note'")

    # kind 欄註解同步（tables.py 已改，兩邊必須逐字一致）
    op.execute(
        "COMMENT ON COLUMN attribution_event_lst.kind IS "
        + _q(
            "事件類型：prejudge（初判快照）/ failure（初判失敗留痕）/ correction（人工糾正）/ "
            "review_confirm（複審確認）/ suggestion（重判轉待審建議）/ "
            "suggestion_resolved（建議採納或駁回）/ "
            "router_shadow（域路由召回量測，內部遙測不進使用者時間軸）。"
            "備註不在此表——見 attribution_note_lst（活查詢鍵不埋 JSONB）"
        )
    )


def downgrade() -> None:
    op.execute(
        """
        INSERT INTO attribution_event_lst
            (feedback_source_code, source_id, kind, note_content, author, create_date)
        SELECT feedback_source_code, source_id, 'note', content, create_user, create_date
        FROM attribution_note_lst
        """
    )
    op.execute("DROP TABLE IF EXISTS attribution_note_lst")
    op.execute("DELETE FROM attribution_dimension_master WHERE dimension_code = 'note_type'")
    op.execute(
        "COMMENT ON COLUMN attribution_event_lst.kind IS "
        + _q(
            "事件類型：prejudge（初判快照）/ note（人工備註）/ failure（初判失敗留痕）/ "
            "router_shadow（域路由召回量測，內部遙測不進使用者時間軸）"
        )
    )


def _q(s: str) -> str:
    """SQL 字串字面量（單引號跳脫）——註解文字含中文引號與 `**`，不可用 f-string 直拼。"""
    return "'" + s.replace("'", "''") + "'"
