"""baseline schema

Revision ID: bd77052f7222
Revises:
Create Date: 2026-06-30 13:04:18.073937

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd77052f7222"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batches",
        sa.Column("batch_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("original_name", sa.Text(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("inserted_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("batch_id"),
    )
    op.create_table(
        "confidence_calibration",
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("intercept", sa.Float(), nullable=True),
        sa.Column("slope", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("scope", "model"),
    )
    op.create_table(
        "intake_items",
        sa.Column("item_id", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("batch_id", sa.Text(), nullable=True),
        sa.Column("prod_oid", sa.Text(), nullable=True),
        sa.Column("pkg_oid", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("raw", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("item_id"),
    )
    op.create_table(
        "judgments",
        sa.Column("finding_id", sa.Text(), nullable=False),
        sa.Column("item_id", sa.Text(), nullable=True),
        sa.Column("prod_oid", sa.Text(), nullable=True),
        sa.Column("pkg_oid", sa.Text(), nullable=True),
        sa.Column("dimension", sa.Text(), nullable=True),
        sa.Column("verdict", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("raw_confidence", sa.Float(), nullable=True),
        sa.Column("is_enhanced", sa.Integer(), server_default="0", nullable=True),
        sa.Column("enhance_model", sa.Text(), nullable=True),
        sa.Column("needs_review", sa.Integer(), server_default="0", nullable=True),
        sa.Column("true_label", sa.Text(), nullable=True),
        sa.Column("suspected_field", sa.Text(), nullable=True),
        sa.Column("recommended_action", sa.Text(), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("data", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("user_settings")
    op.drop_table("judgments")
    op.drop_table("intake_items")
    op.drop_table("confidence_calibration")
    op.drop_table("batches")
    # ### end Alembic commands ###
