"""roster tables

Revision ID: c24e5b0964ce
Revises: bd77052f7222
Create Date: 2026-06-30 13:26:04.366693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24e5b0964ce'
down_revision: Union[str, Sequence[str], None] = 'bd77052f7222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_prod_quality_issue'), table_name='prod_quality')
    op.create_index('idx_prod_quality_issue', 'prod_quality', ['content_issue_n'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prod_quality_issue', table_name='prod_quality')
    op.create_index(op.f('idx_prod_quality_issue'), 'prod_quality', [sa.literal_column('content_issue_n DESC')], unique=False)
    # ### end Alembic commands ###
