"""初判執行日誌拆表：prejudge_run_tbl.log（整批一坨 JSONB）→ prejudge_run_log_lst（一評論一列）

**為什麼要拆**：舊設計把整個 job 的日誌塞在 run 列的 `log` JSONB 欄，導致兩個硬限制——

1. 只能整批結束才寫一次（中途逐筆累加會讓 Postgres 每次 UPDATE 都整列重寫已成長的 blob，
   34k 筆的批次累計寫入量是 O(N²)），於是日誌得先全部堆在記憶體裡；
2. 記憶體 O(批量筆數) 撐不住大批量（實測 43 KB/筆 → 34k 筆約 1.44 GB），只好用
   `LOG_JOB_MAX_ITEMS = 20` 的閘門把大批量全部排除——「批量初判查不到 LLM 日誌」的根因。

拆成一評論一列後：每筆判完即 INSERT（純 append 不重寫）、記憶體佔用降為 O(併發數)，
閘門隨之取消，**所有 job 不分筆數都收日誌**。

**既有資料**：190 列的舊快照按條目的 `item_id` 拆進新表（無 item_id 的 job 級事件歸
`source_id = ''`），拆完 drop 掉 `log` 欄——依專案核心原則 4「退役即徹底」不留相容死欄。

Revision ID: d4b19c7a2e50
Revises: c2d70b9e4f81
Create Date: 2026-08-06

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "d4b19c7a2e50"
down_revision: str | Sequence[str] | None = "c2d70b9e4f81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_LOG_COL_COMMENT = (
    "run_log 快照（entries 陣列）：僅小批量 job 收集，供事後回看完整 LLM 日誌；"
    "run_log 本身純記憶體不落庫"
)

# `log` 欄退場採**重建表**而非 `DROP COLUMN`：PG 的 DROP COLUMN 會在 attnum 留下空洞，
# 於是「跑 migration 鏈的庫」與「create_all 建的新庫」欄序不同（modify_user 落在第 19 vs 18 欄），
# 被 `test_schema_parity` 的 column_order 比對抓出來。作法與 f1b78d3a95c2 一致：
# CREATE 新表 → INSERT SELECT 逐欄具名搬移 → DROP 舊表 → RENAME → 重建約束/索引/註解 → setval。
# ⚠️ 本組 SQL 為凍結快照（產生當下自 metadata 導出後寫死），不在執行期讀 tables.py。
_RUN_TBL_COLS = (
    "prejudge_run_oid, job_id, trigger_kind, is_rejudge, feedback_source_code, model, params, "
    "run_status, total, processed, ok, failed, total_tokens, cost_usd, create_user, create_date, "
    "finished_at, modify_user, modify_date"
)

_REBUILD_RUN_TBL: tuple[str, ...] = (
    "CREATE TABLE prejudge_run_tbl__rebuild ( prejudge_run_oid INTEGER GENERATED BY DEFAULT AS "
    "IDENTITY, job_id TEXT NOT NULL, trigger_kind TEXT NOT NULL, is_rejudge BOOLEAN, "
    "feedback_source_code TEXT, model TEXT, params JSONB, run_status TEXT NOT NULL, total INTEGER, "
    "processed INTEGER, ok INTEGER, failed INTEGER, total_tokens BIGINT, cost_usd FLOAT, "
    "create_user VARCHAR(255), create_date TIMESTAMP WITH TIME ZONE DEFAULT now(), "
    "finished_at TIMESTAMP WITH TIME ZONE, modify_user VARCHAR(255), "
    "modify_date TIMESTAMP WITH TIME ZONE, PRIMARY KEY (prejudge_run_oid) )",
    f"INSERT INTO prejudge_run_tbl__rebuild ({_RUN_TBL_COLS}) OVERRIDING SYSTEM VALUE "
    f"SELECT {_RUN_TBL_COLS} FROM prejudge_run_tbl",
    "DROP TABLE prejudge_run_tbl",
    "ALTER TABLE prejudge_run_tbl__rebuild RENAME TO prejudge_run_tbl",
    "ALTER TABLE prejudge_run_tbl RENAME CONSTRAINT prejudge_run_tbl__rebuild_pkey "
    "TO prejudge_run_tbl_pkey",
    "CREATE INDEX idx_prejudge_run_tbl_create_date ON prejudge_run_tbl (create_date)",
    "CREATE UNIQUE INDEX idx_prejudge_run_tbl_unique01 ON prejudge_run_tbl (job_id)",
    "COMMENT ON TABLE prejudge_run_tbl IS '初判批次執行紀錄（run 級：每次觸發初判的動作落一列）。"
    "與 llm_usage（call 級）以 job_id 關聯——本表存業務語境（誰／何時／範圍／參數／結果統計），"
    "token 與費用明細由 llm_usage 聚合'",
    "COMMENT ON COLUMN prejudge_run_tbl.prejudge_run_oid IS '流水號主鍵（serial）'",
    "COMMENT ON COLUMN prejudge_run_tbl.job_id IS '批次任務 id（pj_* uuid；與 llm_usage.job_id "
    "對齊）。PK 已改為 serial prejudge_run_oid，本欄降為 UNIQUE 業務鍵——它同時是 in-mem registry "
    "的 key 與 SSE 端點的 capability token，語義不可變'",
    "COMMENT ON COLUMN prejudge_run_tbl.trigger_kind IS '觸發型態：batch（依條件批量選取）/ "
    "selected（勾選多筆）/ single（單筆）'",
    "COMMENT ON COLUMN prejudge_run_tbl.is_rejudge IS '標的先前已有初判結果 → 本次為重新初判'",
    "COMMENT ON COLUMN prejudge_run_tbl.feedback_source_code IS '反饋來源 code（reviews…）'",
    "COMMENT ON COLUMN prejudge_run_tbl.model IS '本次使用的初判模型'",
    "COMMENT ON COLUMN prejudge_run_tbl.params IS '發起參數快照（stages/verticals/傾向/信心上限…；"
    "item_ids 只留樣本避免膨脹）'",
    "COMMENT ON COLUMN prejudge_run_tbl.run_status IS 'running / paused / cancelling → 終態 done / "
    "error / cancelled / interrupted（行程重啟）'",
    "COMMENT ON COLUMN prejudge_run_tbl.total IS '本次標的總筆數'",
    "COMMENT ON COLUMN prejudge_run_tbl.processed IS '已處理筆數（終態回寫；執行中由 in-mem 快照 "
    "overlay）'",
    "COMMENT ON COLUMN prejudge_run_tbl.ok IS '成功筆數'",
    "COMMENT ON COLUMN prejudge_run_tbl.failed IS '失敗筆數'",
    "COMMENT ON COLUMN prejudge_run_tbl.total_tokens IS '本 run 累計 token（usage sink 加總）'",
    "COMMENT ON COLUMN prejudge_run_tbl.cost_usd IS '本 run 累計費用（pricing 換算）'",
    "COMMENT ON COLUMN prejudge_run_tbl.create_user IS '觸發人（user email）'",
    "COMMENT ON COLUMN prejudge_run_tbl.create_date IS '開始時間'",
    "COMMENT ON COLUMN prejudge_run_tbl.finished_at IS '結束時間；執行中為空'",
    "COMMENT ON COLUMN prejudge_run_tbl.modify_user IS '最後修改者（user email 或 system:* 標記）'",
    "COMMENT ON COLUMN prejudge_run_tbl.modify_date IS '最後修改時間'",
    "SELECT setval(pg_get_serial_sequence('prejudge_run_tbl', 'prejudge_run_oid'), "
    "GREATEST(COALESCE((SELECT max(prejudge_run_oid) FROM prejudge_run_tbl), 0), 1))",
)


def upgrade() -> None:
    """建新表 → 舊 log 欄按 item_id 拆列搬進去 → 重建 run 表（去掉 log 欄）。"""
    op.create_table(
        "prejudge_run_log_lst",
        sa.Column(
            "prejudge_run_log_oid",
            sa.Integer(),
            sa.Identity(),
            nullable=False,
            comment="流水號主鍵（serial）",
        ),
        sa.Column(
            "job_id",
            sa.Text(),
            nullable=False,
            comment="所屬初判任務 id（與 prejudge_runs.job_id 對齊；無 FK，軟關聯）",
        ),
        sa.Column(
            "source_id",
            sa.Text(),
            nullable=False,
            comment="日誌所屬評論的來源自然鍵；空字串＝job 級事件（任務啟動/收尾，不屬於任何單一評論）",
        ),
        sa.Column(
            "entries",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="該評論本次初判的完整日誌條目陣列（run_log entries 形狀：ts/kind/stage/message/label/data）",
        ),
        sa.Column("create_user", sa.String(255), nullable=True, comment="觸發人（user email）"),
        sa.Column(
            "create_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
            comment="落庫時間（該筆判完即寫，非整批結束才寫）",
        ),
        sa.PrimaryKeyConstraint("prejudge_run_log_oid"),
        comment="初判執行日誌（append-only 明細流水，一則評論一列）：每筆判完即落庫，記憶體佔用與批量大小"
        "脫鉤，故不分批量大小全數收集。刻意不與 prejudge_runs 同列——日誌是數十 KB 的 blob，若塞回 run 列"
        "的 JSONB 欄，逐筆累加會讓 Postgres 每次都整列重寫（O(N²) 寫入放大）",
    )
    op.create_index(
        "idx_prejudge_run_log_lst_unique01",
        "prejudge_run_log_lst",
        ["job_id", "source_id"],
        unique=True,
    )
    op.create_index("idx_prejudge_run_log_lst_create_date", "prejudge_run_log_lst", ["create_date"])
    # 舊快照拆列搬遷：同一 job 內按條目的 item_id 分組，組內維持原陣列順序（WITH ORDINALITY）。
    # 逐評論標記機制上線前的舊快照沒有 item_id → 整批落在 source_id='' 的 job 級列，
    # 前端對這種「未蓋章」快照本來就有混排提示與整批視角回退，行為不變。
    op.execute(
        """
        INSERT INTO prejudge_run_log_lst (job_id, source_id, entries, create_user, create_date)
        SELECT r.job_id,
               coalesce(t.e->>'item_id', ''),
               jsonb_agg(t.e ORDER BY t.ord),
               r.create_user,
               r.create_date
        FROM prejudge_run_tbl r
        CROSS JOIN LATERAL jsonb_array_elements(r.log) WITH ORDINALITY AS t(e, ord)
        WHERE jsonb_typeof(r.log) = 'array'
        GROUP BY r.job_id, coalesce(t.e->>'item_id', ''), r.create_user, r.create_date
        """
    )
    for stmt in _REBUILD_RUN_TBL:  # 去掉 log 欄（重建而非 DROP COLUMN，理由見 _REBUILD_RUN_TBL）
        op.execute(stmt)


def downgrade() -> None:
    """把新表的列重新併回 log 欄（依 ts 遞增還原順序）→ drop 新表。

    ⚠️ 不還原 log 欄的**位置**（ADD COLUMN 一律加在最後）：欄序是純物理排列、不影響查詢語義，
    為回退它再重建一次表風險大於收益（同 f1b78d3a95c2 的取捨）。真要回到舊欄序走 pg_dump 還原。
    """
    op.add_column(
        "prejudge_run_tbl",
        sa.Column(
            "log",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment=_LOG_COL_COMMENT,
        ),
    )
    op.execute(
        """
        UPDATE prejudge_run_tbl r
        SET log = agg.entries
        FROM (
            SELECT l.job_id, jsonb_agg(t.e ORDER BY (t.e->>'ts')::float8) AS entries
            FROM prejudge_run_log_lst l
            CROSS JOIN LATERAL jsonb_array_elements(l.entries) AS t(e)
            GROUP BY l.job_id
        ) agg
        WHERE r.job_id = agg.job_id
        """
    )
    op.drop_index("idx_prejudge_run_log_lst_create_date", table_name="prejudge_run_log_lst")
    op.drop_index("idx_prejudge_run_log_lst_unique01", table_name="prejudge_run_log_lst")
    op.drop_table("prejudge_run_log_lst")
