"""judge_rule_versions

Revision ID: df57def04797
Revises: c24e5b0964ce
Create Date: 2026-06-30 15:17:21.942396

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "df57def04797"
down_revision: str | Sequence[str] | None = "c24e5b0964ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
