"""重建 10 張表以修正欄位順序（PK 置首）+ 消弭 create_all 與 migration 鏈的欄序漂移

PG 不支援 ALTER 欄位順序，唯一辦法是重建：
    CREATE 新表（欄序照 tables.py 宣告序，`<名詞>_oid` 置首）→ INSERT SELECT 搬資料
    → DROP 舊表 → RENAME → 重建索引/註解 → 把 identity 序列推到 max(oid)

**兩個動機**
1. `<名詞>_oid` serial PK 置於第一欄（慣例：主鍵在前，翻表一眼看到身分）
2. **修一個先前沒被發現的漂移**：`ADD COLUMN` 一律把欄位加在最後，於是「跑 migration 鏈的庫」
   與「create_all 建的新庫」欄序不同（attribution_oid 在前者是第 26 欄、後者是第 1 欄）。
   原本的 `test_schema_parity` 是 `ORDER BY 欄名`，天生看不到 ordinal_position 差異——
   本輪替它補上 `column_order` 比對後才暴露出來（10 張表全中，含與本輪無關的 review_tbl）。

⚠️ **本檔 SQL 為凍結快照**：產生當下自 metadata 導出後寫死，不在執行期讀 `tables.py`。
理由同 baseline v2——migration 一旦讀當下的 code，「這支 revision 做了什麼」就不再可重現。

⚠️ **約束名的兩個坑**（皆實測踩過）：
· 具名 UNIQUE 約束**不能**在建 `__rebuild` 表時就帶上——約束名與索引共用命名空間，
  舊表尚存時同名必撞 `DuplicateTable`。抽出來等 RENAME 後再 `ADD CONSTRAINT`。
· `ALTER TABLE ... RENAME TO` **不會改約束名**——PK 會留在 `<表>__rebuild_pkey`，
  破壞先前做到的 `<表>_pkey` 合規。故每張表 RENAME 後都顯式 `RENAME CONSTRAINT`。

⚠️ **資料完整性**：`INSERT ... SELECT` 逐欄具名搬移（非 `SELECT *`），identity 欄以
`OVERRIDING SYSTEM VALUE` 沿用舊 oid，搬完把序列 setval 到 max——既有 oid 不變、新增不撞號。
套用前後逐表對帳列數（見同輪驗證紀錄）。

Revision ID: f1b78d3a95c2
Revises: e2a91c47d0b3
Create Date: 2026-08-04

"""

from collections.abc import Sequence

from alembic import op

revision: str = "f1b78d3a95c2"
down_revision: str | Sequence[str] | None = "e2a91c47d0b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_UPGRADE: tuple[str, ...] = (
    # ── attribution_tbl 重建（欄序照 tables.py，PK 置首）──
    "CREATE TABLE attribution_tbl__rebuild ( attribution_oid INTEGER GENERATED BY DEFAULT AS IDENTITY, feedback_source_code TEXT, source_id TEXT, polarity TEXT, sentiment_score INTEGER, prejudge_stage TEXT, l1_code TEXT, l1_label TEXT, l2_code TEXT, l2_label TEXT, conf_value FLOAT, conf_raw FLOAT, conf_tier TEXT, summary JSONB, evidence TEXT, recommended_action TEXT, model TEXT, is_primary BOOLEAN DEFAULT 'false', is_auto_accepted BOOLEAN DEFAULT 'false', create_date TIMESTAMP WITH TIME ZONE, create_user VARCHAR(36), modify_user VARCHAR(36), modify_date TIMESTAMP WITH TIME ZONE, PRIMARY KEY (attribution_oid) )",
    "INSERT INTO attribution_tbl__rebuild (attribution_oid, feedback_source_code, source_id, polarity, sentiment_score, prejudge_stage, l1_code, l1_label, l2_code, l2_label, conf_value, conf_raw, conf_tier, summary, evidence, recommended_action, model, is_primary, is_auto_accepted, create_date, create_user, modify_user, modify_date) OVERRIDING SYSTEM VALUE SELECT attribution_oid, feedback_source_code, source_id, polarity, sentiment_score, prejudge_stage, l1_code, l1_label, l2_code, l2_label, conf_value, conf_raw, conf_tier, summary, evidence, recommended_action, model, is_primary, is_auto_accepted, create_date, create_user, modify_user, modify_date FROM attribution_tbl",
    "DROP TABLE attribution_tbl",
    "ALTER TABLE attribution_tbl__rebuild RENAME TO attribution_tbl",
    "ALTER TABLE attribution_tbl RENAME CONSTRAINT attribution_tbl__rebuild_pkey TO attribution_tbl_pkey",
    "CREATE INDEX idx_attribution_tbl_mix01 ON attribution_tbl (feedback_source_code, source_id)",
    "CREATE INDEX idx_attribution_tbl_polarity ON attribution_tbl (polarity)",
    "CREATE INDEX idx_attribution_tbl_prejudge_stage ON attribution_tbl (prejudge_stage)",
    "CREATE INDEX idx_attribution_tbl_l1_code ON attribution_tbl (l1_code)",
    "CREATE INDEX idx_attribution_tbl_l2_code ON attribution_tbl (l2_code)",
    "CREATE INDEX idx_attribution_tbl_feedback_source_code ON attribution_tbl (feedback_source_code)",
    "CREATE INDEX idx_attribution_tbl_sentiment_score ON attribution_tbl (sentiment_score)",
    "CREATE INDEX idx_attribution_tbl_conf_tier ON attribution_tbl (conf_tier)",
    "CREATE UNIQUE INDEX idx_attribution_tbl_unique01 ON attribution_tbl (feedback_source_code, source_id, l1_code, l2_code)",
    "COMMENT ON TABLE attribution_tbl IS '初判歸因結果（一列＝一條歸因，同一則反饋可有多列）。全 typed scalar 欄無 JSONB blob——本表是查詢／聚合／篩選密集的分析核心，typed 欄可直接 btree 索引且 SQL 乾淨；巢狀物件屬呈現層，在 API DTO（_shared.attribution_dto）才組。無任何人工可改欄位，重新初判即整組替換'",
    "COMMENT ON COLUMN attribution_tbl.attribution_oid IS '流水號主鍵（serial）'",
    "COMMENT ON COLUMN attribution_tbl.feedback_source_code IS '反饋來源 code，決定關聯哪張來源表（reviews / conversations…）'",
    "COMMENT ON COLUMN attribution_tbl.source_id IS '該來源表的特徵 id 原值（reviews→rec_oid / conversations→session_oid / freshdesk_tickets→id / app_feedback→oid / mixpanel_tracker→insert_id）'",
    "COMMENT ON COLUMN attribution_tbl.polarity IS '情緒傾向：positive / negative / neutral'",
    "COMMENT ON COLUMN attribution_tbl.sentiment_score IS '情緒分 1-5（LLM 讀原文判定，與 polarity 同段輸出：負 1-2 / 中 3 / 正 4-5）——與外部評論 sentiment 同尺度供逐則比對；null＝未初判'",
    "COMMENT ON COLUMN attribution_tbl.prejudge_stage IS '初判完成度：judged（已初判）/ pending_review（待複審）/ pending_data（待數據補充）'",
    "COMMENT ON COLUMN attribution_tbl.l1_code IS 'L1 域代碼（如 content / supplier）'",
    "COMMENT ON COLUMN attribution_tbl.l1_label IS 'L1 域中文名'",
    "COMMENT ON COLUMN attribution_tbl.l2_code IS 'L2 面向代碼（C-N-M）'",
    "COMMENT ON COLUMN attribution_tbl.l2_label IS 'L2 面向中文名'",
    "COMMENT ON COLUMN attribution_tbl.conf_value IS '最終信心值（校準後，0~1）'",
    "COMMENT ON COLUMN attribution_tbl.conf_raw IS 'arbiter LLM 回報的原始信心值（未校準）'",
    "COMMENT ON COLUMN attribution_tbl.conf_tier IS '信心分層：auto_accept（自動採信）/ jury（評審複審）/ needs_review（人工複審）'",
    "COMMENT ON COLUMN attribution_tbl.summary IS '反饋摘要（語系→簡明摘要 map，務必含 zh-tw；表格只顯示 zh-tw，逐字原文佐證另存 evidence）'",
    "COMMENT ON COLUMN attribution_tbl.evidence IS '佐證原文（自反饋原文逐字擷取的片段）'",
    "COMMENT ON COLUMN attribution_tbl.recommended_action IS '建議行動'",
    "COMMENT ON COLUMN attribution_tbl.model IS '產出本列的初判模型；stub 模式為 ''stub'''",
    "COMMENT ON COLUMN attribution_tbl.is_primary IS '多歸因中的主歸因旗標'",
    "COMMENT ON COLUMN attribution_tbl.is_auto_accepted IS '系統是否自動採納：信心達 auto_accept 門檻且非 needs_review 階段時由 prejudge._route_auto_accept 設 true；jury 分層與低信心重路由留 false'",
    "COMMENT ON COLUMN attribution_tbl.create_date IS '初判落庫時間（ISO 8601 字串）＝本列唯一時間源'",
    "COMMENT ON COLUMN attribution_tbl.create_user IS '建立者（user email 或 system:* 標記）'",
    "COMMENT ON COLUMN attribution_tbl.modify_user IS '最後修改者（user email 或 system:* 標記）'",
    "COMMENT ON COLUMN attribution_tbl.modify_date IS '最後修改時間'",
    "SELECT setval(pg_get_serial_sequence('attribution_tbl', 'attribution_oid'), GREATEST(COALESCE((SELECT max(attribution_oid) FROM attribution_tbl), 0), 1))",
    # ── attribution_event_lst 重建（欄序照 tables.py，PK 置首）──
    "CREATE TABLE attribution_event_lst__rebuild ( attribution_event_oid INTEGER GENERATED BY DEFAULT AS IDENTITY, feedback_source_code TEXT NOT NULL, source_id TEXT NOT NULL, kind TEXT NOT NULL, model TEXT, params JSONB, attribution_snapshot JSONB, result_digest TEXT, job_id TEXT, create_user VARCHAR(36), author TEXT, note_content TEXT, create_date TIMESTAMP WITH TIME ZONE DEFAULT now(), PRIMARY KEY (attribution_event_oid) )",
    "INSERT INTO attribution_event_lst__rebuild (attribution_event_oid, feedback_source_code, source_id, kind, model, params, attribution_snapshot, result_digest, job_id, create_user, author, note_content, create_date) OVERRIDING SYSTEM VALUE SELECT attribution_event_oid, feedback_source_code, source_id, kind, model, params, attribution_snapshot, result_digest, job_id, create_user, author, note_content, create_date FROM attribution_event_lst",
    "DROP TABLE attribution_event_lst",
    "ALTER TABLE attribution_event_lst__rebuild RENAME TO attribution_event_lst",
    "ALTER TABLE attribution_event_lst RENAME CONSTRAINT attribution_event_lst__rebuild_pkey TO attribution_event_lst_pkey",
    "CREATE INDEX idx_attribution_event_lst_create_date ON attribution_event_lst (create_date)",
    "CREATE INDEX idx_attribution_event_lst_mix02 ON attribution_event_lst (feedback_source_code, model, source_id, create_date DESC) WHERE kind = 'prejudge'",
    "CREATE INDEX idx_attribution_event_lst_mix01 ON attribution_event_lst (feedback_source_code, source_id, create_date)",
    "COMMENT ON TABLE attribution_event_lst IS '評論級歸因歷史（append-only 事件流）：補 attributions「刪+插」重新初判不留痕的缺口——prejudge_runs 是 run 級、llm_usage 是 call 級，皆無法重建單一評論的初判演進。無 FK，以 (source, source_id) 邏輯鍵關聯（該鍵跨重新初判穩定，不像 finding_id 會斷鏈）'",
    "COMMENT ON COLUMN attribution_event_lst.attribution_event_oid IS '流水號主鍵（serial）'",
    "COMMENT ON COLUMN attribution_event_lst.feedback_source_code IS '反饋來源 code（reviews…）'",
    "COMMENT ON COLUMN attribution_event_lst.source_id IS '該來源的特徵 id（評論級鍵）'",
    "COMMENT ON COLUMN attribution_event_lst.kind IS '事件類型：prejudge（初判快照）/ note（人工備註）/ failure（初判失敗留痕）/ router_shadow（域路由召回量測，內部遙測不進使用者時間軸）'",
    "COMMENT ON COLUMN attribution_event_lst.model IS '初判模型（kind=prejudge）'",
    "COMMENT ON COLUMN attribution_event_lst.params IS '事件細節：prejudge 存 {model,…}（回填列為 {backfilled:true}）；failure 存 {error}；router_shadow 存 {candidates,hit,missed,probs}'",
    "COMMENT ON COLUMN attribution_event_lst.attribution_snapshot IS '初判結果快照（attribution_dto 形狀陣列；僅 kind=prejudge 有值）'",
    "COMMENT ON COLUMN attribution_event_lst.result_digest IS '快照全欄位（排除時間戳）正規化後的 sha256，供相鄰列去重比對'",
    "COMMENT ON COLUMN attribution_event_lst.job_id IS '觸發的批次任務 id（與 prejudge_runs.job_id 對齊）；人工事件為空'",
    "COMMENT ON COLUMN attribution_event_lst.create_user IS '觸發人（user email；kind=prejudge）'",
    "COMMENT ON COLUMN attribution_event_lst.author IS '備註人（user email；kind=note）'",
    "COMMENT ON COLUMN attribution_event_lst.note_content IS '備註內容（kind=note）'",
    "COMMENT ON COLUMN attribution_event_lst.create_date IS '事件時間'",
    "SELECT setval(pg_get_serial_sequence('attribution_event_lst', 'attribution_event_oid'), GREATEST(COALESCE((SELECT max(attribution_event_oid) FROM attribution_event_lst), 0), 1))",
    # ── llm_usage_lst 重建（欄序照 tables.py，PK 置首）──
    "CREATE TABLE llm_usage_lst__rebuild ( llm_usage_oid INTEGER GENERATED BY DEFAULT AS IDENTITY, stage TEXT, model TEXT NOT NULL, prompt_tokens INTEGER, completion_tokens INTEGER, reasoning_tokens INTEGER, cached_tokens INTEGER, total_tokens INTEGER, cost_usd FLOAT, feedback_source_code TEXT, job_id TEXT, create_date TIMESTAMP WITH TIME ZONE DEFAULT now(), create_user VARCHAR(36), PRIMARY KEY (llm_usage_oid) )",
    "INSERT INTO llm_usage_lst__rebuild (llm_usage_oid, stage, model, prompt_tokens, completion_tokens, reasoning_tokens, cached_tokens, total_tokens, cost_usd, feedback_source_code, job_id, create_date, create_user) OVERRIDING SYSTEM VALUE SELECT llm_usage_oid, stage, model, prompt_tokens, completion_tokens, reasoning_tokens, cached_tokens, total_tokens, cost_usd, feedback_source_code, job_id, create_date, create_user FROM llm_usage_lst",
    "DROP TABLE llm_usage_lst",
    "ALTER TABLE llm_usage_lst__rebuild RENAME TO llm_usage_lst",
    "ALTER TABLE llm_usage_lst RENAME CONSTRAINT llm_usage_lst__rebuild_pkey TO llm_usage_lst_pkey",
    "CREATE INDEX idx_llm_usage_lst_model ON llm_usage_lst (model)",
    "CREATE INDEX idx_llm_usage_lst_create_date ON llm_usage_lst (create_date)",
    "CREATE INDEX idx_llm_usage_lst_stage ON llm_usage_lst (stage)",
    "COMMENT ON TABLE llm_usage_lst IS 'AI 使用紀錄（per-call：每次真實 LLM 呼叫落一列），供成本 dashboard 多維度聚合。唯一寫入點＝llm.client 的 usage recorder（批次走 buffer 批量寫、單次即時寫）'",
    "COMMENT ON COLUMN llm_usage_lst.llm_usage_oid IS '流水號主鍵（serial）'",
    "COMMENT ON COLUMN llm_usage_lst.stage IS '呼叫階段：polarity / C-1~C-6 / prompt_debug / prompt_revise…'",
    "COMMENT ON COLUMN llm_usage_lst.model IS '實際使用的模型（cfg.model）'",
    "COMMENT ON COLUMN llm_usage_lst.prompt_tokens IS '輸入 token 數'",
    "COMMENT ON COLUMN llm_usage_lst.completion_tokens IS '輸出 token 數（reasoning model 下已含 reasoning_tokens）'",
    "COMMENT ON COLUMN llm_usage_lst.reasoning_tokens IS 'completion 中屬 reasoning 的部分（reasoning_effort 產出；供量測降檔位的空間）'",
    "COMMENT ON COLUMN llm_usage_lst.cached_tokens IS 'prompt 中命中 prompt cache 的 token 數（折扣計價）'",
    "COMMENT ON COLUMN llm_usage_lst.total_tokens IS 'prompt_tokens + completion_tokens'",
    "COMMENT ON COLUMN llm_usage_lst.cost_usd IS '本次呼叫費用（pricing.cost_usd 換算，含 cache 折扣與 service tier）'",
    "COMMENT ON COLUMN llm_usage_lst.feedback_source_code IS '反饋來源 code（reviews…）；ad-hoc 呼叫為空'",
    "COMMENT ON COLUMN llm_usage_lst.job_id IS '所屬批次任務 id；單次呼叫為空'",
    "COMMENT ON COLUMN llm_usage_lst.create_date IS '呼叫時間'",
    "COMMENT ON COLUMN llm_usage_lst.create_user IS '建立者（user email 或 system:* 標記）'",
    "SELECT setval(pg_get_serial_sequence('llm_usage_lst', 'llm_usage_oid'), GREATEST(COALESCE((SELECT max(llm_usage_oid) FROM llm_usage_lst), 0), 1))",
    # ── prejudge_run_tbl 重建（欄序照 tables.py，PK 置首）──
    "CREATE TABLE prejudge_run_tbl__rebuild ( prejudge_run_oid INTEGER GENERATED BY DEFAULT AS IDENTITY, job_id TEXT NOT NULL, trigger_kind TEXT NOT NULL, rejudge BOOLEAN, feedback_source_code TEXT, model TEXT, params JSONB, run_status TEXT NOT NULL, total INTEGER, processed INTEGER, ok INTEGER, failed INTEGER, total_tokens BIGINT, cost_usd FLOAT, create_user VARCHAR(36), create_date TIMESTAMP WITH TIME ZONE DEFAULT now(), finished_at TIMESTAMP WITH TIME ZONE, log JSONB, modify_user VARCHAR(36), modify_date TIMESTAMP WITH TIME ZONE, PRIMARY KEY (prejudge_run_oid) )",
    "INSERT INTO prejudge_run_tbl__rebuild (prejudge_run_oid, job_id, trigger_kind, rejudge, feedback_source_code, model, params, run_status, total, processed, ok, failed, total_tokens, cost_usd, create_user, create_date, finished_at, log, modify_user, modify_date) OVERRIDING SYSTEM VALUE SELECT prejudge_run_oid, job_id, trigger_kind, rejudge, feedback_source_code, model, params, run_status, total, processed, ok, failed, total_tokens, cost_usd, create_user, create_date, finished_at, log, modify_user, modify_date FROM prejudge_run_tbl",
    "DROP TABLE prejudge_run_tbl",
    "ALTER TABLE prejudge_run_tbl__rebuild RENAME TO prejudge_run_tbl",
    "ALTER TABLE prejudge_run_tbl RENAME CONSTRAINT prejudge_run_tbl__rebuild_pkey TO prejudge_run_tbl_pkey",
    "CREATE INDEX idx_prejudge_run_tbl_create_date ON prejudge_run_tbl (create_date)",
    "CREATE UNIQUE INDEX idx_prejudge_run_tbl_unique01 ON prejudge_run_tbl (job_id)",
    "COMMENT ON TABLE prejudge_run_tbl IS '初判批次執行紀錄（run 級：每次觸發初判的動作落一列）。與 llm_usage（call 級）以 job_id 關聯——本表存業務語境（誰／何時／範圍／參數／結果統計），token 與費用明細由 llm_usage 聚合'",
    "COMMENT ON COLUMN prejudge_run_tbl.prejudge_run_oid IS '流水號主鍵（serial）'",
    "COMMENT ON COLUMN prejudge_run_tbl.job_id IS '批次任務 id（pj_* uuid；與 llm_usage.job_id 對齊）。PK 已改為 serial prejudge_run_oid，本欄降為 UNIQUE 業務鍵——它同時是 in-mem registry 的 key 與 SSE 端點的 capability token，語義不可變'",
    "COMMENT ON COLUMN prejudge_run_tbl.trigger_kind IS '觸發型態：batch（依條件批量選取）/ selected（勾選多筆）/ single（單筆）'",
    "COMMENT ON COLUMN prejudge_run_tbl.rejudge IS '標的先前已有初判結果 → 本次為重新初判'",
    "COMMENT ON COLUMN prejudge_run_tbl.feedback_source_code IS '反饋來源 code（reviews…）'",
    "COMMENT ON COLUMN prejudge_run_tbl.model IS '本次使用的初判模型'",
    "COMMENT ON COLUMN prejudge_run_tbl.params IS '發起參數快照（stages/verticals/傾向/信心上限…；item_ids 只留樣本避免膨脹）'",
    "COMMENT ON COLUMN prejudge_run_tbl.run_status IS 'running / paused / cancelling → 終態 done / error / cancelled / interrupted（行程重啟）'",
    "COMMENT ON COLUMN prejudge_run_tbl.total IS '本次標的總筆數'",
    "COMMENT ON COLUMN prejudge_run_tbl.processed IS '已處理筆數（終態回寫；執行中由 in-mem 快照 overlay）'",
    "COMMENT ON COLUMN prejudge_run_tbl.ok IS '成功筆數'",
    "COMMENT ON COLUMN prejudge_run_tbl.failed IS '失敗筆數'",
    "COMMENT ON COLUMN prejudge_run_tbl.total_tokens IS '本 run 累計 token（usage sink 加總）'",
    "COMMENT ON COLUMN prejudge_run_tbl.cost_usd IS '本 run 累計費用（pricing 換算）'",
    "COMMENT ON COLUMN prejudge_run_tbl.create_user IS '觸發人（user email）'",
    "COMMENT ON COLUMN prejudge_run_tbl.create_date IS '開始時間'",
    "COMMENT ON COLUMN prejudge_run_tbl.finished_at IS '結束時間；執行中為空'",
    "COMMENT ON COLUMN prejudge_run_tbl.log IS 'run_log 快照（entries 陣列）：僅小批量 job 收集，供事後回看完整 LLM 日誌；run_log 本身純記憶體不落庫'",
    "COMMENT ON COLUMN prejudge_run_tbl.modify_user IS '最後修改者（user email 或 system:* 標記）'",
    "COMMENT ON COLUMN prejudge_run_tbl.modify_date IS '最後修改時間'",
    "SELECT setval(pg_get_serial_sequence('prejudge_run_tbl', 'prejudge_run_oid'), GREATEST(COALESCE((SELECT max(prejudge_run_oid) FROM prejudge_run_tbl), 0), 1))",
    # ── judge_rule_version_lst 重建（欄序照 tables.py，PK 置首）──
    "CREATE TABLE judge_rule_version_lst__rebuild ( judge_rule_version_oid INTEGER GENERATED BY DEFAULT AS IDENTITY, rule_code TEXT NOT NULL, version_number INTEGER NOT NULL, rule_content JSONB NOT NULL, note TEXT, create_user VARCHAR(36), is_active BOOLEAN DEFAULT 'false' NOT NULL, create_date TIMESTAMP WITH TIME ZONE DEFAULT now(), PRIMARY KEY (judge_rule_version_oid) )",
    "INSERT INTO judge_rule_version_lst__rebuild (judge_rule_version_oid, rule_code, version_number, rule_content, note, create_user, is_active, create_date) OVERRIDING SYSTEM VALUE SELECT judge_rule_version_oid, rule_code, version_number, rule_content, note, create_user, is_active, create_date FROM judge_rule_version_lst",
    "DROP TABLE judge_rule_version_lst",
    "ALTER TABLE judge_rule_version_lst__rebuild RENAME TO judge_rule_version_lst",
    "ALTER TABLE judge_rule_version_lst RENAME CONSTRAINT judge_rule_version_lst__rebuild_pkey TO judge_rule_version_lst_pkey",
    "ALTER TABLE judge_rule_version_lst ADD CONSTRAINT idx_judge_rule_version_lst_unique01 UNIQUE (rule_code, version_number)",
    "CREATE UNIQUE INDEX idx_judge_rule_version_lst_unique02 ON judge_rule_version_lst (rule_code) WHERE is_active",
    "COMMENT ON TABLE judge_rule_version_lst IS '初判規則版本庫（append-only 快照：每次存檔 insert 新列不就地改，規避 JSONB write-amplification）。檔案 config/*.json 與 prompts/*.md 為默認 seed，本表存 live + 完整歷史'",
    "COMMENT ON COLUMN judge_rule_version_lst.judge_rule_version_oid IS '流水號主鍵（serial）'",
    "COMMENT ON COLUMN judge_rule_version_lst.rule_code IS '規則代碼：bd_tag_vertical / source_mapping / prompt_polarity / prompt_C-1~C-6'",
    "COMMENT ON COLUMN judge_rule_version_lst.version_number IS '版本號，per rule_code 從 1 遞增'",
    "COMMENT ON COLUMN judge_rule_version_lst.rule_content IS '該版本完整內容；prompt_* 為 {_meta, text(md 全文)}'",
    "COMMENT ON COLUMN judge_rule_version_lst.note IS '存檔備註（使用者輸入，說明本次改了什麼）'",
    "COMMENT ON COLUMN judge_rule_version_lst.create_user IS '存檔人（user email）'",
    "COMMENT ON COLUMN judge_rule_version_lst.is_active IS '是否為線上生效版；一 rule_code 僅一筆為 true（由部分唯一索引強制）'",
    "COMMENT ON COLUMN judge_rule_version_lst.create_date IS '存檔時間'",
    "SELECT setval(pg_get_serial_sequence('judge_rule_version_lst', 'judge_rule_version_oid'), GREATEST(COALESCE((SELECT max(judge_rule_version_oid) FROM judge_rule_version_lst), 0), 1))",
    # ── upload_batch_tbl 重建（欄序照 tables.py，PK 置首）──
    "CREATE TABLE upload_batch_tbl__rebuild ( upload_batch_oid INTEGER GENERATED BY DEFAULT AS IDENTITY, batch_id TEXT NOT NULL, batch_name TEXT, feedback_source_code TEXT, original_name TEXT, row_count INTEGER, create_date TIMESTAMP WITH TIME ZONE, note TEXT, create_user VARCHAR(36), modify_user VARCHAR(36), modify_date TIMESTAMP WITH TIME ZONE, PRIMARY KEY (upload_batch_oid) )",
    "INSERT INTO upload_batch_tbl__rebuild (upload_batch_oid, batch_id, batch_name, feedback_source_code, original_name, row_count, create_date, note, create_user, modify_user, modify_date) OVERRIDING SYSTEM VALUE SELECT upload_batch_oid, batch_id, batch_name, feedback_source_code, original_name, row_count, create_date, note, create_user, modify_user, modify_date FROM upload_batch_tbl",
    "DROP TABLE upload_batch_tbl",
    "ALTER TABLE upload_batch_tbl__rebuild RENAME TO upload_batch_tbl",
    "ALTER TABLE upload_batch_tbl RENAME CONSTRAINT upload_batch_tbl__rebuild_pkey TO upload_batch_tbl_pkey",
    "CREATE UNIQUE INDEX idx_upload_batch_tbl_unique01 ON upload_batch_tbl (batch_id)",
    "COMMENT ON TABLE upload_batch_tbl IS '上傳批次審計流水：一列＝一次上傳中的一張工作表，供資料上傳頁回溯來源檔與筆數'",
    "COMMENT ON COLUMN upload_batch_tbl.upload_batch_oid IS '流水號主鍵（serial）'",
    "COMMENT ON COLUMN upload_batch_tbl.batch_id IS '上傳批次 id（uuid hex）'",
    "COMMENT ON COLUMN upload_batch_tbl.batch_name IS '自動命名的批次名「{來源} YYYYMMDD{當天序號:02d}」'",
    "COMMENT ON COLUMN upload_batch_tbl.feedback_source_code IS '反饋來源 code（reviews / conversations…）'",
    "COMMENT ON COLUMN upload_batch_tbl.original_name IS '上傳檔名（多分頁 xlsx 為「檔名::工作表名」）'",
    "COMMENT ON COLUMN upload_batch_tbl.row_count IS '該工作表的資料列數'",
    "COMMENT ON COLUMN upload_batch_tbl.create_date IS '上傳時間（ISO 8601 字串，含時區偏移）'",
    "COMMENT ON COLUMN upload_batch_tbl.note IS '使用者上傳時輸入的備註（每工作表一則，隨批次保存）'",
    "COMMENT ON COLUMN upload_batch_tbl.create_user IS '建立者（user email 或 system:* 標記）'",
    "COMMENT ON COLUMN upload_batch_tbl.modify_user IS '最後修改者（user email 或 system:* 標記）'",
    "COMMENT ON COLUMN upload_batch_tbl.modify_date IS '最後修改時間'",
    "SELECT setval(pg_get_serial_sequence('upload_batch_tbl', 'upload_batch_oid'), GREATEST(COALESCE((SELECT max(upload_batch_oid) FROM upload_batch_tbl), 0), 1))",
    # ── setting_master 重建（欄序照 tables.py，PK 置首）──
    "CREATE TABLE setting_master__rebuild ( setting_oid INTEGER GENERATED BY DEFAULT AS IDENTITY, setting_code TEXT NOT NULL, setting_value TEXT, modify_date TIMESTAMP WITH TIME ZONE, create_user VARCHAR(36), create_date TIMESTAMP WITH TIME ZONE, modify_user VARCHAR(36), PRIMARY KEY (setting_oid) )",
    "INSERT INTO setting_master__rebuild (setting_oid, setting_code, setting_value, modify_date, create_user, create_date, modify_user) OVERRIDING SYSTEM VALUE SELECT setting_oid, setting_code, setting_value, modify_date, create_user, create_date, modify_user FROM setting_master",
    "DROP TABLE setting_master",
    "ALTER TABLE setting_master__rebuild RENAME TO setting_master",
    "ALTER TABLE setting_master RENAME CONSTRAINT setting_master__rebuild_pkey TO setting_master_pkey",
    "CREATE UNIQUE INDEX idx_setting_master_unique01 ON setting_master (setting_code)",
    "COMMENT ON TABLE setting_master IS '全項目共享設定（單例 row，見 core/settings.py）：LLM 連線與模型配置庫、QC DB 連線、功能區綁定、導出偏好。機密欄位加密後才落此表'",
    "COMMENT ON COLUMN setting_master.setting_oid IS '流水號主鍵（serial）'",
    "COMMENT ON COLUMN setting_master.setting_code IS '設定鍵；目前僅單例 ''__global__'''",
    "COMMENT ON COLUMN setting_master.setting_value IS '設定全文 JSON 字串；機密欄位（token/密碼）為 at-rest 密文'",
    "COMMENT ON COLUMN setting_master.modify_date IS '最後更新時間（ISO 8601 字串）'",
    "COMMENT ON COLUMN setting_master.create_user IS '建立者（user email 或 system:* 標記）'",
    "COMMENT ON COLUMN setting_master.create_date IS '建立時間'",
    "COMMENT ON COLUMN setting_master.modify_user IS '最後修改者（user email 或 system:* 標記）'",
    "SELECT setval(pg_get_serial_sequence('setting_master', 'setting_oid'), GREATEST(COALESCE((SELECT max(setting_oid) FROM setting_master), 0), 1))",
    # ── evidence_snapshot_tbl 重建（欄序照 tables.py，PK 置首）──
    "CREATE TABLE evidence_snapshot_tbl__rebuild ( evidence_snapshot_oid INTEGER GENERATED BY DEFAULT AS IDENTITY, order_oid BIGINT NOT NULL, order_mid TEXT, order_status TEXT, price_pay FLOAT, lang_code TEXT, crt_dt TIMESTAMP WITH TIME ZONE, prod_oid BIGINT, prod_version BIGINT, pkg_oid BIGINT, item_oid BIGINT, supplier_oid BIGINT, lst_dt_go TIMESTAMP WITH TIME ZONE, product_timezone TEXT, pkg_name TEXT, prod_desc TEXT, supplier_name TEXT, supplier_order_handler TEXT, supplier_msg_handler TEXT, product_summary JSONB, product_desc_module JSONB, item_lang JSONB, item_setting JSONB, package_lang JSONB, package_setting JSONB, package_policy JSONB, package_module_setting JSONB, create_date TIMESTAMP WITH TIME ZONE, expires_at TIMESTAMP WITH TIME ZONE, create_user VARCHAR(36), modify_user VARCHAR(36), modify_date TIMESTAMP WITH TIME ZONE, PRIMARY KEY (evidence_snapshot_oid) )",
    "INSERT INTO evidence_snapshot_tbl__rebuild (evidence_snapshot_oid, order_oid, order_mid, order_status, price_pay, lang_code, crt_dt, prod_oid, prod_version, pkg_oid, item_oid, supplier_oid, lst_dt_go, product_timezone, pkg_name, prod_desc, supplier_name, supplier_order_handler, supplier_msg_handler, product_summary, product_desc_module, item_lang, item_setting, package_lang, package_setting, package_policy, package_module_setting, create_date, expires_at, create_user, modify_user, modify_date) OVERRIDING SYSTEM VALUE SELECT evidence_snapshot_oid, order_oid, order_mid, order_status, price_pay, lang_code, crt_dt, prod_oid, prod_version, pkg_oid, item_oid, supplier_oid, lst_dt_go, product_timezone, pkg_name, prod_desc, supplier_name, supplier_order_handler, supplier_msg_handler, product_summary, product_desc_module, item_lang, item_setting, package_lang, package_setting, package_policy, package_module_setting, create_date, expires_at, create_user, modify_user, modify_date FROM evidence_snapshot_tbl",
    "DROP TABLE evidence_snapshot_tbl",
    "ALTER TABLE evidence_snapshot_tbl__rebuild RENAME TO evidence_snapshot_tbl",
    "ALTER TABLE evidence_snapshot_tbl RENAME CONSTRAINT evidence_snapshot_tbl__rebuild_pkey TO evidence_snapshot_tbl_pkey",
    "CREATE INDEX idx_evidence_snapshot_tbl_prod_oid ON evidence_snapshot_tbl (prod_oid)",
    "CREATE UNIQUE INDEX idx_evidence_snapshot_tbl_unique01 ON evidence_snapshot_tbl (order_oid)",
    "CREATE INDEX idx_evidence_snapshot_tbl_supplier_oid ON evidence_snapshot_tbl (supplier_oid)",
    "CREATE INDEX idx_evidence_snapshot_tbl_expires_at ON evidence_snapshot_tbl (expires_at)",
    "COMMENT ON TABLE evidence_snapshot_tbl IS '訂單佐證快照（qc_evidence 的 PG 快取層）：下單當時的商品／規格／方案內容投影，一訂單一列 + TTL 懶清理。runtime 派生快取（真相源＝production snapshot，可重生），刻意不入資料包。欄位徹底拆開而非單一 payload jsonb——ID／純量各自成欄便於 grid 核對，內容各自獨立 jsonb 欄'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.evidence_snapshot_oid IS '流水號主鍵（serial）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.order_oid IS '訂單 oid（一訂單一列）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.order_mid IS '訂單編號（對外顯示用的訂單號）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.order_status IS '下單當時的訂單狀態'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.price_pay IS '實付金額'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.lang_code IS '訂單語系'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.crt_dt IS '訂單建立時間'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.prod_oid IS '商品 oid'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.prod_version IS '下單當時的商品版本號（佐證取的是這一版內容）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.pkg_oid IS '方案 oid（來源欄 prod_level2_oid）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.item_oid IS '規格 oid'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.supplier_oid IS '供應商 oid'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.lst_dt_go IS '出發／使用日期'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.product_timezone IS '商品所在時區'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.pkg_name IS '方案名稱（來源欄 prod_level2_name）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.prod_desc IS '商品名稱／描述'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.supplier_name IS '供應商名稱'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.supplier_order_handler IS '訂單處理方（KKDAY / SUPPLIER）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.supplier_msg_handler IS '訊息處理方（KKDAY / SUPPLIER）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.product_summary IS '商品摘要：category / timezone / product_name(單語) / sale_time_result'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.product_desc_module IS '商品描述模組（單語渲染：行程／注意事項／介紹…）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.item_lang IS '規格渲染文案（來源 ors_prod_lang.item_summary）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.item_setting IS '規格設定：spec_rule / price / quantity（來源 ors_prod_setting.item_summary）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.package_lang IS '方案渲染文案（來源 ors_prod_lang.package_summary）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.package_setting IS '本方案設定：多語名稱 / GPM / 退改（來源 ors_prod_setting.package_summary）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.package_policy IS '方案政策：cancel_policy_client + tour_duration（來源 ors_pkg_basic）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.package_module_setting IS '方案模組設定 list[{prod_module_type,…}]（來源 ors_prod_module_setting）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.create_date IS '本列自 production 取數的時間'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.expires_at IS '快取到期時間；讀到過期視為 miss 並刪列'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.create_user IS '建立者（user email 或 system:* 標記）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.modify_user IS '最後修改者（user email 或 system:* 標記）'",
    "COMMENT ON COLUMN evidence_snapshot_tbl.modify_date IS '最後修改時間'",
    "SELECT setval(pg_get_serial_sequence('evidence_snapshot_tbl', 'evidence_snapshot_oid'), GREATEST(COALESCE((SELECT max(evidence_snapshot_oid) FROM evidence_snapshot_tbl), 0), 1))",
    # ── review_tbl 重建（欄序照 tables.py，PK 置首）──
    "CREATE TABLE review_tbl__rebuild ( rec_oid TEXT NOT NULL, review_external_lst_oid TEXT, create_date TEXT, rec_title TEXT, rec_desc TEXT, rec_scores TEXT, traveller_type TEXT, lang_code TEXT, sentiment TEXT, free_tag TEXT, member_uuid TEXT, order_oid TEXT, order_mid TEXT, order_create_time TEXT, order_lang TEXT, go_date TEXT, order_price TEXT, order_profit TEXT, order_create_source_code TEXT, prod_oid TEXT, pkg_oid TEXT, product_name TEXT, order_snap_json TEXT, bd_tag_cd TEXT, bd_tag TEXT, supplier_oid TEXT, supplier_name TEXT, PRIMARY KEY (rec_oid) )",
    "INSERT INTO review_tbl__rebuild (rec_oid, review_external_lst_oid, create_date, rec_title, rec_desc, rec_scores, traveller_type, lang_code, sentiment, free_tag, member_uuid, order_oid, order_mid, order_create_time, order_lang, go_date, order_price, order_profit, order_create_source_code, prod_oid, pkg_oid, product_name, order_snap_json, bd_tag_cd, bd_tag, supplier_oid, supplier_name) SELECT rec_oid, review_external_lst_oid, create_date, rec_title, rec_desc, rec_scores, traveller_type, lang_code, sentiment, free_tag, member_uuid, order_oid, order_mid, order_create_time, order_lang, go_date, order_price, order_profit, order_create_source_code, prod_oid, pkg_oid, product_name, order_snap_json, bd_tag_cd, bd_tag, supplier_oid, supplier_name FROM review_tbl",
    "DROP TABLE review_tbl",
    "ALTER TABLE review_tbl__rebuild RENAME TO review_tbl",
    "ALTER TABLE review_tbl RENAME CONSTRAINT review_tbl__rebuild_pkey TO review_tbl_pkey",
    "CREATE INDEX idx_review_tbl_create_date ON review_tbl (create_date)",
    "CREATE INDEX idx_review_tbl_prod_oid ON review_tbl (prod_oid)",
    "COMMENT ON TABLE review_tbl IS '商品評論來源鏡像（忠實鏡射上游 BQ 取數輸出：欄名與型別逐欄對齊，不做 canonical 化）。一列＝一則評論，PK rec_oid'",
)


def upgrade() -> None:
    """逐表重建以修正欄序；資料逐欄具名搬移，oid 沿用。"""
    for stmt in _UPGRADE:
        op.execute(stmt)


def downgrade() -> None:
    """不還原欄序。

    欄序是純物理排列、不影響任何查詢語義；為了回退它而再重建一次 10 張表，
    風險遠大於收益。真要回到舊欄序請走 pg_dump 備份還原。
    """
